const maquinasMock = [
  {
    "id": 1,
    "codigo": "120LVR-01PLN3.AA",
    "nome": "Motoniveladora",
    "modelo": "120 NG",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+120%20NG",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALAVANCAS, TOP ADJUST, TELA TOUCH SCREEN, MEDIDOR DIGITAL DE INCLINAÇÃO DA LAMINA, LUZES EM LED, LÂMINA DE 4,3M  , RIPPER C/ 5 DENTES, PNEU DIAGONAL 17.5-25 16 LONAS",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "15.699Kg",
      "Motor": "C7.1 - 125hp",
      "Ferramentas": "LÂMINA DE 4,3M  , RIPPER C/ 5 DENTES",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1238383.5,
      "3% ACIMA": 1215400,
      "VALOR FEIRA": 1180000,
      "BORSO": 30000,
      "DESCONTO ": 0.08,
      "MARGEM": 0.0851,
      "BUYDOWN": 0
    }
  },
  {
    "id": 2,
    "codigo": "140GC-01GLN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 GC",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "NACIONAL, ALAVANCAS, LUZES HALÓGENAS, LÂMINA DE 4,3M  , RIPPER C/ 5 DENTES E ESCARIFICADOR C/ 9 DENTES, PNEU DIAGONAL 17.5-25 16 LONAS",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "17.305Kg",
      "Motor": "C7.1 - 176hp",
      "Ferramentas": "LÂMINA DE 4,3M  , RIPPER C/ 5 DENTES E ESCARIFICADOR C/ 9 DENTES",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "17.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.11,
      "Preço CPQ 14%": 1119790.03,
      "3% ACIMA": 1102100,
      "VALOR FEIRA": 1070000,
      "BORSO": 30000,
      "DESCONTO ": 0.13,
      "MARGEM": 0.08349999999999999,
      "BUYDOWN": 0
    }
  },
  {
    "id": 3,
    "codigo": "140JOY-02ELN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 JOY",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20JOY",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " 3D SEM MASTRO, CROSS SLOPE (2D), STABLE BLADE, AUTO-ARTICULAÇÃO, TOP ADJUST, LUZES EM LED",
      "Contato com o solo": "PNEU RADIAL 17.5 - 25",
      "Peso Operacional": "18.400Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "17.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1636055.44,
      "BUYDOWN": 0
    }
  },
  {
    "id": 4,
    "codigo": "140LVR3-01ALN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 NG",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20NG",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALAVANCAS, TOP ADJUST, TELA TOUCH SCREEN, MEDIDOR DIGITAL DE INCLINAÇÃO DA LAMINA, ACUMULADORES DE IMPACTO, LUZES EM LED, LÂMINA DE 4,3M  , RIPPER+ESCARIFICADOR C/ 5<(>&<)>9 DENTES, PNEU DIAGONAL 17.5-25 16 LONAS",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "18.400Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1422911.88,
      "Opcionais": "Luz em Led, Tela Touch e Top Adjust",
      "Preço opcionais": 37000,
      "3% ACIMA": 1493500,
      "VALOR FEIRA": 1450000,
      "BORSO": 20000,
      "DESCONTO ": 0.06,
      "MARGEM": 0.1161,
      "BUYDOWN": 0
    }
  },
  {
    "id": 5,
    "codigo": "150JOY-01ELN3.AA",
    "nome": "Motoniveladora",
    "modelo": "150 JOY",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+150%20JOY",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " JOY, CROSS SLOPE (2D), STABLE BLADE, AUTO-ARTICULAÇÃO, TOP ADJUST, LUZES EM LED",
      "Contato com o solo": "PNEU RADIAL 17.5R25",
      "Peso Operacional": "18.991Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1687877.88,
      "BUYDOWN": 0
    }
  },
  {
    "id": 6,
    "codigo": "160JOY-01DLN3.AA",
    "nome": "Motoniveladora",
    "modelo": "160 JOY",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+160%20JOY",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "LUZ DE LED, ARO + CROSS SLOPE + STABLE BLADE + CONTROLE AUTOMÁTICO DE ARTICULAÇÃO",
      "Contato com o solo": "PNEUS 17.5R25 MICHELIM",
      "Peso Operacional": "20.607Kg",
      "Motor": "C9 - 213hp",
      "Ferramentas": "LÂMINA DE 4,3M PLUS, RIPPER/ESCARIFICADOR C/ 9 DENTES",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "22.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1771111.94,
      "BUYDOWN": 0
    }
  },
  {
    "id": 7,
    "codigo": "226B3-01PDC.AA",
    "nome": "Minicarregadeira",
    "modelo": "226 B3",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+226%20B3",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "JOYSTICK PILOTADO, CABINE COM AR",
      "Contato com o solo": "Pneu ",
      "Peso Operacional": "2.641Kg",
      "Motor": "C2.2T - 56hp",
      "Ferramentas": "CACAMBA 1730MM E 0,40 M³, BORDA",
      "Capacidade": "Carga max levantamento 680Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.05,
      "Preço CPQ 14%": 336883.64,
      "BUYDOWN": 0
    }
  },
  {
    "id": 8,
    "codigo": "250-03BLN2.AA",
    "nome": "Minicarregadeira",
    "modelo": "250",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+250",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "FLUXO PADRÃO (STANDARD FLOW), CAPACIDADE OPERACIONAL 1220 KG, JOYSTICK ELETRONICO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, 1 VELOCIDADE, PNEU 10/16,5, ASSENTO VINIL, SEM CONTRAPESO, CACAMBA 1883MM",
      "Contato com o solo": "PNEU 10/16,5",
      "Peso Operacional": "3.551Kg",
      "Motor": "C2.8T - 74hp",
      "Ferramentas": "CACAMBA 1883MM",
      "Capacidade": "Carga max levantamento 1.220Kg",
      "Consumo Garantido": "5.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 370295.28,
      "Opcionais": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS), JOYSTICK AVANÇADO, MONITOR AVANÇADO, 2 VELOCIDADES, ASSENTO TECIDO, CONTRAPESO ADICIONAL",
      "Preço opcionais": 25500,
      "3% ACIMA": 381100,
      "VALOR FEIRA": 370000,
      "BORSO": 10000,
      "DESCONTO ": 0.05,
      "MARGEM": 0.0818,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 9,
    "codigo": "260-02ALN3.AA",
    "nome": "Minicarregadeira",
    "modelo": "260",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+260",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS, CAPACIDADE OPERACIONAL 1540 KG, JOYSTICK AVANÇADO, MONITOR AVANÇADO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, 2 VELOCIDADES, PNEU 12/16,5, ASSENTO TECIDO, CONTRAPESO ADICIONAL, CACAMBA 2036MM",
      "Contato com o solo": " PNEU 12/16,5",
      "Peso Operacional": "3.866Kg",
      "Motor": "C2.8T - 74hp",
      "Ferramentas": "CACAMBA 2036MM",
      "Capacidade": "Carga max levantamento1.540Kg",
      "Consumo Garantido": "6.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.05,
      "Preço CPQ 14%": 438417.45,
      "3% ACIMA": 453200,
      "VALOR FEIRA": 440000,
      "BORSO": 10000,
      "DESCONTO ": 0.05,
      "MARGEM": 0.0836,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 10,
    "codigo": "270-01LN3.AA",
    "nome": "Minicarregadeira",
    "modelo": "270",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+270",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS,  JOYSTICK AVANÇADO, MONITOR AVANÇADO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, CAMERAS LATERAIS, 2 VELOCIDADES,  CONTRAPESO",
      "Contato com o solo": "PNEU 14/17,5",
      "Peso Operacional": "4.736Kg",
      "Motor": "C3.6T - 100hp",
      "Ferramentas": "CAÇAMBA 2184mm 0,63M³ E 9 DENTES",
      "Capacidade": "Carga max levantamento1.776Kg",
      "Consumo Garantido": "6.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 522045.68,
      "BUYDOWN": 0
    }
  },
  {
    "id": 11,
    "codigo": "302.7-03APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "302.7",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+302.7",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "TOLDO, ESTEIRA DE AÇO, ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE ABERTA REBATÍVEL, CAÇAMBA DE 0,08M³ E 460MM",
      "Contato com o solo": "ESTEIRA DE AÇO",
      "Peso Operacional": "2.925Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,08M³ E 460MM",
      "Capacidade": "Profundidade max escav. 2.710mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.14,
      "Preço CPQ 14%": 274265.87,
      "Opcionais": "Cabine fechada com ar condicionado, esteira de aço ou borracha",
      "Preço opcionais": 25000,
      "3% ACIMA": 272950,
      "VALOR FEIRA": 265000,
      "BORSO": 5000,
      "DESCONTO ": 0.12,
      "MARGEM": 0.0555,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 12,
    "codigo": "303.5-02APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "303.5",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+303.5",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CABINE FECHADA, ENGATE RAPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REVATÍVEL",
      "Contato com o solo": "ESTEIRA DE BORRACHA",
      "Peso Operacional": "4.190Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,12M³ E 619MM",
      "Capacidade": "Profundidade max escav. 3.110mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.095,
      "Preço CPQ 14%": 338458.57,
      "Opcionais": "Esteira de aço",
      "Preço opcionais": 5900,
      "BUYDOWN": 0
    }
  },
  {
    "id": 13,
    "codigo": "307-01ALN3.AA",
    "nome": "Miniescavadeira",
    "modelo": "307",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+307",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " CABINE FECHADA E AR CONDIOCIONADO",
      "Contato com o solo": "ESTEIRAS DE AÇO",
      "Peso Operacional": "7.500Kg",
      "Motor": "C2.4T - 49hp",
      "Ferramentas": "CAÇAMBA DE 0,33M³ E LARGURA DE 854MM",
      "Capacidade": "Profundidade max escav. 4.067mm",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.095,
      "BUYDOWN": 0
    }
  },
  {
    "id": 14,
    "codigo": "313GC-01DLN2.AA",
    "nome": "Escavadeira",
    "modelo": "313 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+313%20GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CONSTRUÇÃO GERAL: CABINE ROPS,SAPATA TRIPLA 600MM, BRACO 2,5M, LANCA 4,65M, PROTEÇÃO DO SWIVEL, CAÇ GD 0,53M³",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "12.400Kg",
      "Motor": "C3.6 - 95hp",
      "Ferramentas": "CAÇAMBA GD 0,53M³",
      "Capacidade": "Profundidade max escav. 5.570mm ",
      "Consumo Garantido": "9.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.1,
      "Preço CPQ 14%": 589014.02,
      "3% ACIMA": 571650,
      "VALOR FEIRA": 555000,
      "BORSO": 10000,
      "DESCONTO ": 0.1,
      "MARGEM": 0.0883,
      "BUYDOWN": 0.045
    }
  },
  {
    "id": 15,
    "codigo": "316GC-03FLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316%20GC",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE ROPS, BRACO 2.5M HD, LANCA 4,65M",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "14.600Kg",
      "Motor": "C3.6 - 104hp",
      "Ferramentas": "CAÇ SD 0,65M³ (5 DENTES)",
      "Capacidade": "Profundidade max escav. 5.530mm ",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 688013.41,
      "Opcionais": "Braço 3,0m e Valvula aux com linha",
      "Preço opcionais": 4400,
      "BUYDOWN": 0
    }
  },
  {
    "id": 16,
    "codigo": "318GC-01BLN2.AA",
    "nome": "Escavadeira",
    "modelo": "318GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+318GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "TERRAPLANAGEM: CABINE ROPS, VALVULA AUXILIAR MARTELO SEM LINHA, SAPATA GARRA TRIPLA 700MM, BRACO 2,6M, LANCA 5,1M, CAÇ GD 0,91M",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Peso Operacional": "17.500Kg",
      "Motor": "C3.6 - 111hp",
      "Ferramentas": "CAÇ SD 0,91M",
      "Capacidade": "Profundidade max escav. 6.110mm ",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 745471.73,
      "Opcionais": "Valvula 2 sentidos e linha hidraulica aux",
      "Preço opcionais": 30000,
      "3% ACIMA": 726150,
      "VALOR FEIRA": 705000,
      "BORSO": 15000,
      "DESCONTO ": 0.1,
      "MARGEM": 0.1009,
      "BUYDOWN": 0.045
    }
  },
  {
    "id": 17,
    "codigo": "320-01ULN3.AA",
    "nome": "Escavadeira",
    "modelo": "320",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "TERRAPLANAGEM: VALVULA AUXILIAR, SAPATA GARRA TRIPLA 700MM, BRACO HD 2,9M, LANCA HD 5,7M, CAÇ HD 1,4M³",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Peso Operacional": "21.300Kg",
      "Motor": "C7.1 - 157hp",
      "Ferramentas": "CAÇ HD 1,4M³",
      "Capacidade": "Profundidade max escav. 6.720mm ",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 893506.86,
      "Opcionais": "VALVULA AUXILIAR (2 SENTIDOS) + LINHA",
      "Preço opcionais": 25700,
      "3% ACIMA": 865200,
      "VALOR FEIRA": 840000,
      "BORSO": 15000,
      "DESCONTO ": 0.12,
      "MARGEM": 0.0892,
      "BUYDOWN": 0.05
    }
  },
  {
    "id": 18,
    "codigo": "320GC-01RLN2.AA",
    "nome": "Escavadeira",
    "modelo": "320 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320%20GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "TERRAPLANAGEM: CARRO MÉDIO, VALVULA AUXILIAR, BRACO 2,9M, LANCA 5,7M, CAÇ 1,16M³",
      "Contato com o solo": "CARRO MÉDIO",
      "Peso Operacional": "20.400Kg",
      "Motor": "C4.4 - 143hp",
      "Ferramentas": "CAÇ GD 1,16M³",
      "Capacidade": "Profundidade max escav. 6.630mm ",
      "Consumo Garantido": "12.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 784212.58,
      "Opcionais": "Linha hidraulica aux",
      "Preço opcionais": 18700,
      "3% ACIMA": 787950,
      "VALOR FEIRA": 765000,
      "BORSO": 10000,
      "DESCONTO ": 0.12,
      "MARGEM": 0.0796,
      "BUYDOWN": 0.045
    }
  },
  {
    "id": 19,
    "codigo": "323-01QLN2.AA",
    "nome": "Escavadeira",
    "modelo": "323",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+323",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "VALVULA AUXILIAR, BRACO HD 2,5M, LANCA HD 5,7M",
      "Contato com o solo": "SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "22.900Kg",
      "Motor": "C7.1 - 157hp",
      "Ferramentas": "CAÇ HD 1,56M³",
      "Capacidade": "Profundidade max escav. 6.730mm ",
      "Consumo Garantido": "17.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.12,
      "Preço CPQ 14%": 962613.54,
      "BUYDOWN": 0
    }
  },
  {
    "id": 20,
    "codigo": "336-01HLN2.AA",
    "nome": "Escavadeira",
    "modelo": "336",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+336",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PROTECAO COMPLETA ROLETES, BRACO 2,55M, LANCA 6,18M",
      "Contato com o solo": "CARRO INFERIOR ESTREITO, SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "37.500Kg",
      "Motor": "C7.1 TTA - 306hp",
      "Ferramentas": "CAÇ 2,4M³ COM PROTETOR LATERAL",
      "Capacidade": "Profundidade max escav. 7.510mm ",
      "Consumo Garantido": "26.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 1364832.22,
      "Opcionais": "VALVULA E LINHA PARA MARTELO",
      "Preço opcionais": 33000,
      "BUYDOWN": 0
    }
  },
  {
    "id": 21,
    "codigo": "340-01BLN3.AA",
    "nome": "Escavadeira",
    "modelo": "340",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+340",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PEDREIRA/MINERAÇÃO: VENTILADOR REVERSÍVEL, PROTECAO COMPLETA ROLETES,BRACO 2,55M, LANCA 6,18M",
      "Contato com o solo": "SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "36.800Kg",
      "Motor": "C9.3B - 346hp",
      "Ferramentas": "CAÇ 2,6M³ COM PROTETOR LATERAL",
      "Capacidade": "Profundidade max escav. 7.480mm ",
      "Consumo Garantido": "28.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.052,
      "Preço CPQ 14%": 1610725.98,
      "BUYDOWN": 0
    }
  },
  {
    "id": 22,
    "codigo": "350-04CLN3.AA",
    "nome": "Escavadeira",
    "modelo": "350",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+350",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "SEM TECNOLOGIA: CABINE DELUXE, MONITOR 10\", LANÇA MASSA 6,55M, BRAÇO DE 2.5M, PROTEÇÃO COMPLETA DOS ROLETES, VENTILADOR REVERSÍVEL, CÂMERA TRASEIRA, VÁLVULA PARA MARTELO",
      "Contato com o solo": "SAPATA DG 600MM",
      "Peso Operacional": "47.600Kg",
      "Motor": "C9.3B - 420hp",
      "Ferramentas": "CAÇAMBA SD 3.21M3",
      "Capacidade": "Profundidade max escav. 7.690mm ",
      "Consumo Garantido": "34.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 1941370.92,
      "Opcionais": "Tecnologia de corte + CÂMERA 360, LINHA PARA MARTELO, BOMBA DE REABASTECIMENTO, LUZES NO CONTRAPESO, LUZES DE INSPEÇÃO, Sapata dupla",
      "Preço opcionais": 330000,
      "BUYDOWN": 0
    }
  },
  {
    "id": 23,
    "codigo": "416-02CLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "CABINE, 4X4, 4 FUNÇÕES, DENTES,PL,ESTAB. DE BORRACHA",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 - 87hp",
      "Ferramentas": "Caçamba GP 1,0m³ e 0,23m³",
      "Capacidade": "Profundidade escav. 4.277mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 465433.42,
      "Opcionais": " 1 FUNÇÃO Extra, KEYPAD, PARALAMA,ESTAB. DE BORRACHA",
      "Preço opcionais": 8700,
      "Opcionais_1": " 1 FUNÇÃO Extra + Linha, KEYPAD, PARALAMA,ESTAB. DE BORRACHA",
      "Preço opcionais_1": 23900,
      "Opcionais_2": " 1 FUNÇÃO Extra + Linha, POWERSHIFT, PROT. DO TANQUE, ENGATE RAPIDO.",
      "Preço opcionais_2": 45300,
      "Opcionais_3": "MARTELO B8S, 1 FUNÇÃO Extra + Linha, KEYPAD, PARALAMA,ESTAB. DE BORRACHA",
      "Preço opcionais_3": 69600,
      "Opcionais_4": "5 FUNÇÕES,  BRAÇO EXTENSÍVEL, PARALAMA, ESTAB. DE BORRACHA",
      "Preço opcionais_4": 30400,
      "3% ACIMA": 432600,
      "VALOR FEIRA": 420000,
      "BORSO": 5000,
      "DESCONTO ": 0.113,
      "MARGEM": 0.0861,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 24,
    "codigo": "420-01CLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "420",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+420",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES, DENTE, ESTAB. DE BORRACHA, PARALAMA, KEYPAD, PL",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 - 94hp",
      "Ferramentas": "Caçamba GP 1,0m³ e 0,23m132",
      "Capacidade": "Profundidade escav. 4.278mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.113,
      "Preço CPQ 14%": 504558.49,
      "3% ACIMA": 509850,
      "VALOR FEIRA": 495000,
      "BORSO": 10000,
      "DESCONTO ": 0.113,
      "MARGEM": 0.1046,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 25,
    "codigo": "914-01LN3.AA",
    "nome": "Carregadeira",
    "modelo": "914",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+914",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "Não Encontrada",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Peso Operacional": "8.568Kg",
      "Motor": "C4.4 - 100hp",
      "Ferramentas": "CAÇ 1,6M³ (PO) BORDA",
      "Capacidade": "Peso Max.  2.736Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.055,
      "Preço CPQ 14%": 511439.34,
      "3% ACIMA": 545900,
      "VALOR FEIRA": 530000,
      "BORSO": 15000,
      "DESCONTO ": 0.06,
      "MARGEM": 0.1065,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 26,
    "codigo": "920-01ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PNEU 17.5-25 L2 GD,  CAÇ 1,9M³ (PO) BORDA, REC. ELETR, PL, PROT DO A/C, VENTILADOR REVERSIVEL",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Peso Operacional": "9.132Kg",
      "Motor": "C4.4 - 100hp",
      "Ferramentas": "CAÇ 1,9M³ (PO) BORDA",
      "Capacidade": "Peso Max.  2.703Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 584303.08,
      "Opcionais": "Engate Rápido IT",
      "Preço opcionais": 72800,
      "Opcionais_1": "Pneu Michelin 20,5",
      "Preço opcionais_1": 46900,
      "Opcionais_2": "Engate rápido e Pneu Michelin 20,5",
      "Preço opcionais_2": 60800,
      "3% ACIMA": 576800,
      "VALOR FEIRA": 560000,
      "BORSO": 10000,
      "DESCONTO ": 0.115,
      "MARGEM": 0.10490000000000001,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 27,
    "codigo": "924-03CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "MERCADO GERAL: PNEU DIAGONAL 17.5-25 TITAN, CAÇAMBA 2.1M³ (PINADO) DENTES, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 TITAN",
      "Peso Operacional": "11.775Kg",
      "Motor": "C7.1 - 137hp",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Capacidade": "Peso Max. 3.749Kg",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 746508.86,
      "Opcionais": "PNEU RADIAL 20.5R-25 MAXAM",
      "Preço opcionais": 16600,
      "Opcionais_1": "PNEU RADIAL 20.5R25 MICHELIN",
      "Preço opcionais_1": 58300,
      "Opcionais_2": "Engate rápido FUSION, CONTRAPESO ADICIONAL, PNEU DIAGONAL 20.5-25 TITAN",
      "Preço opcionais_2": 46000,
      "Opcionais_3": "ENGATE: ENGATE RÁPIDO, PNEU DIAGONAL 17.5-25 GOODYEAR",
      "Preço opcionais_3": 49700,
      "3% ACIMA": 736450,
      "VALOR FEIRA": 715000,
      "BORSO": 15000,
      "DESCONTO ": 0.12300000000000001,
      "MARGEM": 0.1025,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 28,
    "codigo": "930-01ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "930",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+930",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PNEU RADIAL 20.5R-25 MAXAM, CAÇAMBA 2.5M³ (PINADO) DENTES, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO).",
      "Contato com o solo": "PNEU RADIAL 20.5R-25 MAXAM",
      "Peso Operacional": "13.246Kg",
      "Motor": "C7.1 - 160hp",
      "Ferramentas": "CAÇAMBA 2.5M³, DENTES",
      "Capacidade": "Peso Max. 4.182Kg",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.152,
      "Preço CPQ 14%": 920568.2,
      "3% ACIMA": 925970,
      "VALOR FEIRA": 899000,
      "BORSO": 20000,
      "DESCONTO ": 0.152,
      "MARGEM": 0.1197,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 29,
    "codigo": "938-01ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "938",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+938",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CANA-DE-AÇÚCAR BAGAÇO VOLANTE: PNEU AGRÍCOLA 750/65R26 MICHELIN, VOLANTE, CAÇAMBA BAGAÇO 6.0M³ (PO) BORDAS, MONITOR 8\", CÂMERA DE RÉ, HÉLICE REVERSÍVEL, FARÓIS LED, PRODUCT LINK DUAL (HÍBRIDO), ASSENTO PREMIUM, GIROFLEX.",
      "Contato com o solo": "PNEU AGRÍCOLA 750/65R26 MICHELIN",
      "Peso Operacional": "15.399Kg",
      "Motor": "C7.1 - 188hp",
      "Ferramentas": "CAÇAMBA BAGAÇO 6.0M³ (PO) BORDAS",
      "Capacidade": "Peso Max. 5.061Kg",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.086,
      "Preço CPQ 14%": 1117274.89,
      "3% ACIMA": 1163900,
      "VALOR FEIRA": 1130000,
      "BORSO": 30000,
      "DESCONTO ": 0.13,
      "MARGEM": 0.15539999999999998,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 30,
    "codigo": "938-04BLN2.AA",
    "nome": "Carregadeira",
    "modelo": "938",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+938",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "CONTRUÇÃO: PNEU RADIAL 20.5R25 MICHELIN, CAÇAMBA 2.7M³ (PINADO) DENTES, VENTILADOR REVERSÍVEL, MONITOR 8\", CÂMERA DE RÉ, ASSENTO COM SENSOR DE PRESENÇA, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU RADIAL 20.5R25 MICHELIN",
      "Peso Operacional": "15.399Kg",
      "Motor": "C7.1 - 188hp",
      "Ferramentas": "CAÇAMBA 2.7M³, DENTES",
      "Capacidade": "Peso Max. 5.061Kg",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.086,
      "Preço CPQ 14%": 1104638.82,
      "3% ACIMA": 1071200,
      "VALOR FEIRA": 1040000,
      "BORSO": 20000,
      "DESCONTO ": 0.13,
      "MARGEM": 0.1032,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 31,
    "codigo": "950-01CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "950",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+950",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ROCHA, 2V SEM RIDE CONTROL , EIXO ARREFECIDO, LUZES HALÓGENAS PREMIUM, VENTILADOR PADRÃO, PRÉ-PURIFICADOR TURBINA, CONTRAPESO AUXILIAR",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "18.076Kg",
      "Motor": "C7.1 - 253hp",
      "Ferramentas": "CAÇAMBA ROCHA 2.90m³",
      "Capacidade": "Peso Max. 5.468Kg",
      "Consumo Garantido": "15.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1468290.84,
      "BUYDOWN": 0
    }
  },
  {
    "id": 32,
    "codigo": "950GC-01HLN2.AA",
    "nome": "Carregadeira",
    "modelo": "950GC",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+950GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PAYLOAD, EIXO ARREFECIDO, 2V SEM RIDE CONTROL, 04 LUZES HALÓGENAS, VENTILADOR REVERSÍVEL, PRÉ-PURIFICADOR TURBINA, CONTRAPESO PADRÃO, CAÇAMBA GP 3.40m³, PNEUS L3",
      "Contato com o solo": "PNEUS L3",
      "Peso Operacional": "18.676Kg",
      "Motor": "C7.1 - 202hp",
      "Ferramentas": "CAÇAMBA GP 3.40m³",
      "Capacidade": "Peso Max. 5.468Kg",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1095369.5,
      "3% ACIMA": 1102100,
      "VALOR FEIRA": 1070000,
      "BORSO": 20000,
      "DESCONTO ": 0.06,
      "MARGEM": 0.0952,
      "BUYDOWN": 0
    }
  },
  {
    "id": 33,
    "codigo": "962-01CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "962",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+962",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ROCHA: EIXO ARREFECIDO, CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEU 23.5R25 L5 MICHELIM",
      "Peso Operacional": "19.043Kg",
      "Motor": "C7.1 - 273hp",
      "Ferramentas": "CAÇ ROCHA 3,1M³ (PO)",
      "Capacidade": "Peso Max. 9.904Kg",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1524307.28,
      "BUYDOWN": 0
    }
  },
  {
    "id": 34,
    "codigo": "966-01ELN3.AA",
    "nome": "Carregadeira",
    "modelo": "966",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+966",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ROCHA, 2V SEM RIDE CONTROL , EIXO ARREFECIDO, LUZES HALÓGENAS PREMIUM, VENTILADOR PADRÃO,  CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "23.196Kg",
      "Motor": "C9.3B - 325hp",
      "Ferramentas": "CAÇAMBA ROCHA 3.40m³",
      "Capacidade": "Peso Max. 7.424Kg",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1793392.4,
      "BUYDOWN": 0
    }
  },
  {
    "id": 35,
    "codigo": "972-02ILN3.AA",
    "nome": "Carregadeira",
    "modelo": "972",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+972",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CERAMICA/AGREGADO, 2V COM RIDE CONTROL, CAMERA TRASEIRA, EIXO ARREFECIDO, CONTRAPESO AGREGADO, VENTILADOR REVERSÍVEL, LUZES HALÓGENAS PREMIUM, PAYLOAD ADVANCED, AUTOLUBE",
      "Contato com o solo": "PNEUS L3",
      "Peso Operacional": "24.890Kg",
      "Motor": "C9.3B - 344hp",
      "Ferramentas": "CAÇAMBA GP 5.30m³",
      "Capacidade": "Peso Max. 8.148Kg",
      "Consumo Garantido": "20.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1910860.47,
      "BUYDOWN": 0
    }
  },
  {
    "id": 36,
    "codigo": "980-02ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "980",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+980",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " MINERIO DE FERRO, 2V COM RIDE CONTROL, EIXO ARREFECIDO, LUZES LED PREMIUM, VENTILADOR PADRÃO, PRÉ-PURIFICADOR TURBINA, CAT DETECT, CONTRAPESO AGREGADO",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "30.344Kg",
      "Motor": "C13 - 417hp",
      "Ferramentas": "CAÇAMBA IRON 3,80m³",
      "Capacidade": "Peso Max. 9.853",
      "Consumo Garantido": "27.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 2755824.79,
      "BUYDOWN": 0
    }
  },
  {
    "id": 37,
    "codigo": "CB10-01DLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB10",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB10",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, SENSOR DE TEMPERATURA, 5 AMPLITUDES E 1 FREQUENCIA",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "9.500Kg",
      "Motor": "C4.4 - 131,8hp",
      "Ferramentas": "1700mm (0,18mm e 0,84mm)",
      "Capacidade": "Peso Max 10.510Kg",
      "Consumo Garantido": "6.5 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.088,
      "Preço CPQ 14%": 698765.22,
      "BUYDOWN": 0
    }
  },
  {
    "id": 38,
    "codigo": "CB2_5GC-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB2.5",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB2.5",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ROPS, 2 AJUSTES DE FREQUENCIA DE 62 E 50HZ",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "2.521Kg",
      "Motor": "C1.7T - 24,7hp",
      "Ferramentas": "1000mm x 720mm (0,51mm)",
      "Capacidade": "Peso Max 3.021Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.068,
      "BUYDOWN": 0
    }
  },
  {
    "id": 39,
    "codigo": "CB2_7GC-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB2.7",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB2.7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ROPS, 2 AJUSTES DE FREQUENCIA DE 62 E 50HZ",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "2.698Kg",
      "Motor": "C1.7T - 24,7hp",
      "Ferramentas": "1200mm x 720mm (0,52mm)",
      "Capacidade": "Peso Max 3.198Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.068,
      "BUYDOWN": 0
    }
  },
  {
    "id": 40,
    "codigo": "CB7-01DLN2.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB7",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, SENSOR DE TEMPERATURA, 2 AMPLITUDES E 2 FREQUENCIAS",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "7.990Kg",
      "Motor": "C2.2 - 49,1hp",
      "Ferramentas": "1500mm (",
      "Capacidade": "Peso Max 8.940Kg",
      "Consumo Garantido": "6.5 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.088,
      "Preço CPQ 14%": 645092.97,
      "BUYDOWN": 0
    }
  },
  {
    "id": 41,
    "codigo": "CC4_0-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CC4.0",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CC4.0",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "2 AJUSTES DE FREQUÊNCIA DE 55 E 48HZ",
      "Contato com o solo": "Chapa - Pneu",
      "Peso Operacional": "3.378Kg",
      "Motor": "C2.2 - 49,1hp",
      "Ferramentas": "800mm (0,5mm)",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.068,
      "BUYDOWN": 0
    }
  },
  {
    "id": 42,
    "codigo": "CP11-02LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CP11",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CP11",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CABINE,MDP",
      "Contato com o solo": "Patas",
      "Peso Operacional": "11.383Kg",
      "Motor": "C4.4 - 130hp",
      "Capacidade": "Largura de Compactação:  2.134mm",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 747147.08,
      "BUYDOWN": 0
    }
  },
  {
    "id": 43,
    "codigo": "CP11GC-02ELN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CP11GC",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CP11GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CABINE PREMIUM, MDP, ASSENTO DE TECIDO",
      "Contato com o solo": "Patas",
      "Peso Operacional": "11.387Kg",
      "Motor": "C4.4 - 112hp",
      "Ferramentas": "2134mm x 1549mm",
      "Capacidade": "Largura de Compactação:  2.134mm",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 654496.76,
      "BUYDOWN": 0
    }
  },
  {
    "id": 44,
    "codigo": "CS10GC-01FLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS10GC",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS10GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE PREMIUM, KIT PATAS, MDP, ASSENTO DE TECIDO",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "10.492Kg",
      "Motor": "C4.4 - 112hp",
      "Ferramentas": "2134mm x 1535mm",
      "Capacidade": "Largura de Compactação:  2.134mm",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 622646.33,
      "3% ACIMA": 602550,
      "VALOR FEIRA": 585000,
      "BORSO": 10000,
      "DESCONTO ": 0.115,
      "MARGEM": 0.102,
      "BUYDOWN": 0
    }
  },
  {
    "id": 45,
    "codigo": "CS11-04ALN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS11",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS11",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": " CABINE, KIT PATAS, MDP",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "10.806Kg",
      "Motor": "C4.4 - 130hp",
      "Ferramentas": "2134mm x 1535mm",
      "Capacidade": "Largura de Compactação:  2.134mm",
      "Consumo Garantido": "13.5 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 748578.73,
      "BUYDOWN": 0
    }
  },
  {
    "id": 46,
    "codigo": "CS11GC-01GLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS11GC",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS11GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE PREMIUM, KIT PATAS, MDP, ASSENTO DE TECIDO",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "11.235Kg",
      "Motor": "C4.4 - 112hp",
      "Ferramentas": "2134mm x 1535mm",
      "Capacidade": "Largura de Compactação:  2.134mm",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 659264.12,
      "3% ACIMA": 638600,
      "VALOR FEIRA": 620000,
      "BORSO": 10000,
      "DESCONTO ": 0.115,
      "MARGEM": 0.1045,
      "BUYDOWN": 0
    }
  },
  {
    "id": 47,
    "codigo": "CS20-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS20",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS20",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "AMPLITUDE ALTA DE 2,1MM E AMPLITUDE BAIXA DE 0,98MM.",
      "Contato com o solo": "Patas",
      "Peso Operacional": "20.220Kg",
      "Motor": "C7.1 - 173hp",
      "Ferramentas": "2134mm x 1535mm",
      "Capacidade": "Largura de Compactação:  2.134mm",
      "Consumo Garantido": "18.5 L/h",
      "Fabricação": "Importado",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "BUYDOWN": 0
    }
  },
  {
    "id": 48,
    "codigo": "CS7-03BLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS7",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS7",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE, KIT PATAS, SEM MDP",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "7.210Kg",
      "Motor": "C4.4 - 131hp",
      "Ferramentas": "1676mm x 1221mm",
      "Capacidade": "Largura de Compactação:  1.676mm",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 485106.28,
      "BUYDOWN": 0
    }
  },
  {
    "id": 49,
    "codigo": "CW34-01HLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CW34",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CW34",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "27.000Kg",
      "Motor": "C4.4 - 100hp",
      "Ferramentas": "2090mm",
      "Capacidade": "Largura de Compactação:  2.090mm",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "PCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.103,
      "Preço CPQ 14%": 797908.14,
      "3% ACIMA": 757050,
      "VALOR FEIRA": 735000,
      "BORSO": 15000,
      "DESCONTO ": 0.14300000000000002,
      "MARGEM": 0.076,
      "BUYDOWN": 0
    }
  },
  {
    "id": 50,
    "codigo": "D4-01ELN2.AA",
    "nome": "Trator Esteiras",
    "modelo": "D4",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D4",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "LÂMINA VPAT DE 3.3m³, SAPATA DE 560mm, GRADE 2D, CÂMERA DE RÉ, PRÉ- PURIFICADOR TURBINA, VENTILADOR REVERSÍVEL, LUZES EM LED, RIPPER COM 3 DENTES",
      "Contato com o solo": "SAPATA DE 560mm",
      "Peso Operacional": "13.500Kg",
      "Motor": "C7.1 - 130hp",
      "Ferramentas": "LÂMINA VPAT DE 3.3m³, RIPPER COM 3 DENTES",
      "Capacidade": "3,8 m³",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1128748.12,
      "3% ACIMA": 1117550,
      "VALOR FEIRA": 1085000,
      "BORSO": 40000,
      "DESCONTO ": 0.06,
      "MARGEM": 0.0603,
      "BUYDOWN": 0
    }
  },
  {
    "id": 51,
    "codigo": "D5-01JLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D5",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D5",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "VPAT, SAPATA 560MM ES HDXL CTWS, PRÉ-PURIFICADOR TURBINA, TELA TOUCHSCRREN 10\", COM TECNOLOGIA 2D, 06 LUZES EM LED, VENTILADOR REVERSÍVEL, RIPPER COM 3 DENTES",
      "Contato com o solo": "SAPATA 560MM ES HDXL CTWS",
      "Peso Operacional": "19.070Kg",
      "Motor": "C7.1 - 170hp",
      "Ferramentas": "LÂMINA VPAT DE 3.3m³, RIPPER COM 3 DENTES",
      "Capacidade": "4m³",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1460542.41,
      "3% ACIMA": 1452300,
      "VALOR FEIRA": 1410000,
      "BORSO": 60000,
      "DESCONTO ": 0.06,
      "MARGEM": 0.0584,
      "BUYDOWN": 0
    }
  },
  {
    "id": 52,
    "codigo": "D5-08CLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D5",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D5",
    "detalhes": {
      "Arranjo": "08",
      "Configuração": "FINE GRADING, PRÉ- PURIFICADOR TURBINA, TELA TOUCHSCRREN 10\", COM TECNOLOGIA 2D, 06 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": " SAPATA 600MM ES HDXL CTWS",
      "Peso Operacional": "19.070Kg",
      "Motor": "C7.1 - 170hp",
      "Ferramentas": "LÂMINA VPAT 4.0M³, RIPPER COM 3 DENTES",
      "Capacidade": "4m³",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.113,
      "Preço CPQ 14%": 1448725.19,
      "BUYDOWN": 0
    }
  },
  {
    "id": 53,
    "codigo": "D6-01BLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D6",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D6",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "TELA TOUCHSCREEN 10\", SEM TECNOLOGIA, CAMERA TRASEIRA, 06 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": "ESTEIRA 560MM ES HDXL",
      "Peso Operacional": "22.130Kg",
      "Motor": "C9.3B - 215hp",
      "Ferramentas": "LÂMINA SU, RIPPER 3 DENTES",
      "Capacidade": "7m³",
      "Consumo Garantido": "25.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1907203.65,
      "BUYDOWN": 0
    }
  },
  {
    "id": 54,
    "codigo": "D7-01CLN3ARO.AA",
    "nome": "Trator Esteiras",
    "modelo": "D7",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PRÉ- PURIFICADOR TURBINA, TROCA DE ÓLEO RÁPIDA, TELA TOUCHSCREEN 10\", CAMERA TRASEIRA, 12 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": " ESTEIRA 560MM ES HD CTWS",
      "Peso Operacional": "29.776Kg",
      "Motor": "C9.3B - 265hp",
      "Ferramentas": "LÂMINA SU, RIPPER 3 DENTES",
      "Capacidade": "9,7 m³",
      "Consumo Garantido": "32.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 2934133.03,
      "BUYDOWN": 0
    }
  },
  {
    "id": 55,
    "codigo": "D8-02CLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D8",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D8",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "SINGLE TILT, PRÉ-PURIFICADOR TURBINA, TROCA DE ÓLEO RÁPIDA, VENTILADOR REVERSÍVEL, TELA TOUCHSCREEN 10\", COM GRADE 2D, CAMERA TRASEIRA, 12 LUZES EM LED",
      "Contato com o solo": "ESTEIRA 610MM ES HD CTWS",
      "Peso Operacional": "39.000Kg",
      "Motor": "C15 - 363hp",
      "Ferramentas": "LÂMINA SU, RIPPER UNIDENTE COM SACO PINO",
      "Capacidade": "10,3m³",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 3851645.03,
      "BUYDOWN": 0
    }
  },
  {
    "id": 56,
    "codigo": "MH3032-01LN3.AA",
    "nome": "Manipulador Hidraulico",
    "modelo": "MH3032",
    "familia": "Manipulador Hidraulico",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+MH3032",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALCANCE MÁXIMO DE CARREGAMENTO DE 14.840 MM, ALTURA MÁXIMA DE 16.270 MM",
      "Contato com o solo": "Pneus duplado",
      "Peso Operacional": "34.500Kg",
      "Motor": "C7.1 - 212hp",
      "Ferramentas": "Garra ",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "WHEX",
      "Industria": "GCI",
      "BUYDOWN": 0
    }
  },
  {
    "id": 57,
    "codigo": "SEM618D-03.SM",
    "nome": "Carregadeira",
    "modelo": "SEM618D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM618D",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CARREGADEIRAS DE RODAS, ARTICULADAS, AUTOPROPULSADA, DE CARREGAMENTO FRONTAL, COM CAPACIDADE DE CAÇAMBA DE 1.0M³ E 1.800KG, POTENCIA NOMINAL BRUTA DE 62,5KW (84HP), POTENCIA NO VOLANTE DE 62,5KW, MOTOR DE 4,7 LITROS DE CILINDRADAS, 2.200 RPM, MOTOR YTO STAGE IIIA, MODELO YT4A4ZU22/0625, COMBUSTÍVEL DIESEL, TRANSMISSÃO ZL15, EIXO ZL16, COM DISPOSITIVO DE ENGATE RÁPIDO COM PINO HORIZONTAL, CAÇAMBA, GARFO PALLET, 3a VALVULA E AR CONDICIONADO MODELO SEM618D, MARCA SEM.",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "5.780Kg",
      "Motor": "YTO 4.7 - 84hp",
      "Ferramentas": "CACAMBA DE 1.0M3 e  GARFO PALLET",
      "Capacidade": "1.800Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "3% ACIMA": 278100,
      "VALOR FEIRA": 270000,
      "BORSO": 10000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 58,
    "codigo": "SEM618D-05.SM",
    "nome": "Carregadeira",
    "modelo": "SEM618D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM618D",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "CARREGADEIRAS DE RODAS, ARTICULADAS, DE CARREGAMENTO FRONTAL, MARCA SEM, MODELO SEM618D, AUTOPROPULSADA, COMBUSTIVEL DIESEL, COM MOTOR YTO STAGE IIIA, MODELO YT4A4ZU22/0625, COM CAPACIDADE DE CAÇAMBA DE 1.0M³ E 1.800KG , POTENCIA NOMINAL BRUTA DE 62,5KW/84HP, MOTOR DE 4,7 LITROS DE CILINDRADAS, 2.200 RPM,TRANSMISSÃO ZL15, EIXO ZL16.",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "5.780Kg",
      "Motor": "YTO 4.7 - 84hp",
      "Ferramentas": "CACAMBA DE 1.0M3",
      "Capacidade": "1.800Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "3% ACIMA": 267800,
      "VALOR FEIRA": 260000,
      "BORSO": 10000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 59,
    "codigo": "SEM636D-07PLA.SM",
    "nome": "Carregadeira",
    "modelo": "SEM636D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM636D",
    "detalhes": {
      "Arranjo": "07",
      "Configuração": "CARREGADEIRA DE RODAS, ARTICULADA,AUTOPROPULSADA, DE CARREGAMENTO FRONTAL, PINADA, MARCA SEM, MODELO SEM636D, COM COMBUSTIVEL DIESEL, COM MOTOR WEICHAI, TIER III(MAR-1), MODELO WP6G125E333, POTENCIA BRUTA 92KW,CACAMBA DE 1.7M3 E 3 TON DE CAPACIDADE DE CARGA, TRANSMISSAO SEM, 2a.VALVULA E AR CONDICIONADO",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "5.780Kg",
      "Motor": "WEICHAI",
      "Ferramentas": "CACAMBA DE 1,7M3",
      "Capacidade": "3.000Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "3% ACIMA": 412000,
      "VALOR FEIRA": 400000,
      "BORSO": 10000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 60,
    "codigo": "SEM636D-08PL.SM",
    "nome": "Carregadeira",
    "modelo": "SEM636D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM636D",
    "detalhes": {
      "Arranjo": "08",
      "Configuração": "CARREGADEIRA DE RODAS, ARTICULADA, AUTOPROPULSADA, DE CARREGAMENTO FRONTAL, COM ENGATE RAPIDO-QC, MARCA SEM, MODELO SEM636D, COM COMBUSTIVEL DIESEL, COM MOTOR WEICHAI, TIER III(MAR-1), MODELO WP6G125E333, POTENCIA BRUTA 92KW, POTENCIA NO VOLANTE DE 92KW, CACAMBA DE 1.7M3 E 3 TON DE CAPACIDADE DE CARGA, TRANSMISSAO SEM, 2a.VALVULA E AR CONDICIONADO.",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "5.780Kg",
      "Motor": "WEICHAI",
      "Ferramentas": "CACAMBA DE 1,7M4",
      "Capacidade": "3.000Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "3% ACIMA": 442900,
      "VALOR FEIRA": 430000,
      "BORSO": 10000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 61,
    "codigo": "SEM656D-03B.SM",
    "nome": "Carregadeira",
    "modelo": "SEM656D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM656D",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CARREGADEIRA DE RODAS, AUTOPROPULSADA, MARCA SEM, MODELO 656D, MOTOR WEICHAI WP10G210 9,7L COM POTENCIA DE 206HP@2000RPM, CARREGAMENTO FRONTAL SOBRE RODAS E PNEUS, TRANSMISSAO SEM TR200 F4/R4, CACAMBA 3M3 PS, PESO OPERACIONAL COM CACAMBA PADRAO DE 17.000KG, COMBUSTIVEL DIESEL, 2a. VALVULA E AR CONDICIONADO.",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "17.000Kg",
      "Motor": "WEICHAI 9.7 - 206hp",
      "Ferramentas": "CACAMBA 3M3 PS",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "3% ACIMA": 628300,
      "VALOR FEIRA": 610000,
      "BORSO": 20000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 62,
    "codigo": "SEM915F-02.SM",
    "nome": "Motoniveladora",
    "modelo": "SEM915F",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM915F",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "MOTONIVELADORA, MARCA SEM MODELO 915F, AUTOPROPULSADA, COMBUSTIVEL DIESEL, COM MOTOR SDEC MODELO SC7H170G3, POTÊNCIA NOMINAL DE 123KW (164,95HP), POTENCIA NO VOLANTE DE 123,00KW, CABINE STD, RIPPER TRASEIRO COM 3 DENTES, COM LARGURA DA LÂMINA DE 3.7M, TRANSMISSÃO HANGCHI 6YD13 TIPOPOWERSHIFT, PREPARACAO PARA EMPLACAMENTO E PNEUS 14.0-24 TL12PR L2",
      "Contato com o solo": "PNEUS 14.0-24 TL12PR L2",
      "Peso Operacional": "13.700Kg",
      "Motor": "SDEC - 165hp",
      "Ferramentas": "LÂMINA DE 3.7M, RIPPER TRASEIRO COM 3 DENTES",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "MG",
      "Industria": "GCI",
      "3% ACIMA": 772500,
      "VALOR FEIRA": 750000,
      "BORSO": 20000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 63,
    "codigo": "SEM919BRZ-01APLB.SM",
    "nome": "Motoniveladora",
    "modelo": "SEM919",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM919",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "MOTONIVELADORA AUTOPROPULSADA, COM ARTICULAÇÃO CENTRAL, EQUIPADA COM CABINE, COM MOTOR DE IGNIÇÃO POR COMPRESSÃO (DIESEL) PERKINS MODELO 1106D-7.01L, POTÊNCIA NO VOLANTE DE 150,9 KW (202HP), FORCA MÁXIMA NA BARRA DE TRAÇÃO DE 78 KN, EIXO ST23, TRANSMISSÃO HANGCHI 6WG 180 AUTOMÁTICA, ALTURA MÁXIMA DE LEVANTAMENTO DA LAMINA DE 715 MM, RIPPER TRASEIRO COM 3 DENTES, PREPARADA PARA EMPLACAMENTO, MARCA SEM, MODELO 919.",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "17.370Kg",
      "Motor": "PERKINS 7.0 - ",
      "Ferramentas": "RIPPER TRASEIRO COM 3 DENTES",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "MG",
      "Industria": "GCI",
      "3% ACIMA": 824000,
      "VALOR FEIRA": 800000,
      "BORSO": 20000,
      "DESCONTO ": "-",
      "MARGEM": 0,
      "BUYDOWN": 0
    }
  },
  {
    "id": 64,
    "codigo": "140-01LN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 NG",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20NG",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALAVANCAS, TOP ADJUST, TELA TOUCH SCREEN, MEDIDOR DIGITAL DE INCLINAÇÃO DA LAMINA, ACUMULADORES DE IMPACTO, LUZES EM LED, LÂMINA DE 4,3M  , RIPPER+ESCARIFICADOR C/ 5<(>&<)>9 DENTES, PNEU DIAGONAL 17.5-25 16 LONAS",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "18.400Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1459941.02,
      "3% ACIMA": 1493500,
      "VALOR FEIRA": 1450000,
      "BORSO": 20000,
      "DESCONTO ": 0.06,
      "MARGEM": 0.1161,
      "BUYDOWN": 0
    }
  },
  {
    "id": 65,
    "codigo": "250-04BLN2.AA",
    "nome": "Minicarregadeira",
    "modelo": "250",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+250",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS), CAPACIDADE OPERACIONAL 1325 KG, JOYSTICK AVANÇADO, MONITOR AVANÇADO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, 2 VELOCIDADES, PNEU 12/16,5, ASSENTO TECIDO, CONTRAPESO ADICIONAL E CACAMBA 1883MM",
      "Contato com o solo": "PNEU 12/16,5",
      "Peso Operacional": "3.551Kg",
      "Motor": "C2.8T - 74hp",
      "Ferramentas": "CACAMBA 1883MM",
      "Capacidade": "Carga max levantamento1.325Kg",
      "Consumo Garantido": "5.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 395906.48,
      "3% ACIMA": 406850,
      "VALOR FEIRA": 395000,
      "BORSO": 10000,
      "DESCONTO ": 0.05,
      "MARGEM": 0.0846,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 66,
    "codigo": "302.7-01APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "302.7",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+302.7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE FECHADA,  ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REBATÍVEL",
      "Contato com o solo": "ESTEIRAS DE AÇO",
      "Peso Operacional": "3.050Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,08M³ E 460MM",
      "Capacidade": "Profundidade max escav. 2.710mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.14,
      "Preço CPQ 14%": 299684.41,
      "BUYDOWN": 0
    }
  },
  {
    "id": 67,
    "codigo": "302.7-02APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "302.7",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+302.7",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "CABINE FECHADA,  ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REBATÍVEL",
      "Contato com o solo": "ESTEIRAS DE BORRACHA",
      "Peso Operacional": "3.050Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇMABA DE 0,08M³ E 460MM",
      "Capacidade": "Profundidade max escav. 2.710mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.14,
      "Preço CPQ 14%": 293868.96,
      "BUYDOWN": 0
    }
  },
  {
    "id": 68,
    "codigo": "303.5-01APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "303.5",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+303.5",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE  FECHADA, ESTEIRA DE AÇO, ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REBATÍVEL, CAÇAMBA DE 0,12M³ E 619MM",
      "Contato com o solo": "ESTEIRA DE AÇO",
      "Peso Operacional": "4.190Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,12M³ E 619MM",
      "Capacidade": "Profundidade max escav. 3.110mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.12,
      "Preço CPQ 14%": 344361.45,
      "3% ACIMA": 325480,
      "VALOR FEIRA": 316000,
      "BORSO": 5000,
      "DESCONTO ": 0.12,
      "MARGEM": 0.0592,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 69,
    "codigo": "316GC-02DLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316%20GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "TERRAPLANAGEM ALCANCE: CABINE ROPS, BRACO 3.0M, LANCA 4,65M",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "14.600Kg",
      "Motor": "C3.6 - 104hp",
      "Ferramentas": "CAÇ GD 0,76M³ (7 DENTES)",
      "Capacidade": "Profundidade max escav. 5.530mm ",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 695674.74,
      "BUYDOWN": 0
    }
  },
  {
    "id": 70,
    "codigo": "316GC-04DLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316%20GC",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "TERRAPLANAGEM ALCANCE VALVULA SD: CABINE ROPS, VALVULA AUXILIAR (2 SENTIDOS) E LINHA, BRACO 3.0M, LANCA 4,65M",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "14.600Kg",
      "Motor": "C3.6 - 104hp",
      "Ferramentas": "CAÇ 0,65M³ (5 DENTES)",
      "Capacidade": "Profundidade max escav. 5.530mm ",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 692417.95,
      "BUYDOWN": 0
    }
  },
  {
    "id": 71,
    "codigo": "318GC-02BLN3.AA",
    "nome": "Escavadeira",
    "modelo": "318GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+318GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "TERRAPLANAGEM COM LINHA: VALVULA AUXILIAR (2 SENTIDOS) + LINHA, SAPATA GARRA TRIPLA 700MM, BRACO 2,6M, LANCA 5,1M, CAÇ GD 0,91M",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Peso Operacional": "17.500Kg",
      "Motor": "C3.6 113hp",
      "Ferramentas": "CAÇ GD 0,91M",
      "Capacidade": "Profundida max escav. 6.110mm",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 775889.96,
      "3% ACIMA": 772500,
      "VALOR FEIRA": 750000,
      "BORSO": 15000,
      "DESCONTO ": 0.1,
      "MARGEM": 0.08310000000000001,
      "BUYDOWN": 0.045
    }
  },
  {
    "id": 72,
    "codigo": "320-02MLN3.AA",
    "nome": "Escavadeira",
    "modelo": "320",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "VALVULA AUXILIAR (2 SENTIDOS) + LINHA, SAPATA GARRA TRIPLA 700MM, BRACO HD 2,9M, LANCA HD 5,7M, CAÇ HD 1,4M³",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Peso Operacional": "21.700Kg",
      "Motor": "C7.1 157hp",
      "Ferramentas": "CAÇ HD 1,4M³",
      "Capacidade": "Profundidade max escav. 6.720mm ",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.12,
      "Preço CPQ 14%": 919211.12,
      "3% ACIMA": 885800,
      "VALOR FEIRA": 860000,
      "BORSO": 15000,
      "DESCONTO ": 0.12,
      "MARGEM": 0.0855,
      "BUYDOWN": 0.05
    }
  },
  {
    "id": 73,
    "codigo": "320GC-02OLN3.AA",
    "nome": "Escavadeira",
    "modelo": "320 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320%20GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "TERRAPLANAGEM VALVULA AUX: CARRO MÉDIO, VALVULA AUXILIAR E LINHA MARTELO, BRACO 2,9M, LANCA 5,7M, CAÇ GD 1,16M³",
      "Contato com o solo": "CARRO MÉDIO",
      "Peso Operacional": "20.000Kg",
      "Motor": "C4.4 143hp",
      "Ferramentas": "CAÇ GD 1,16M³",
      "Capacidade": "Profundidade max escav. 6.630mm ",
      "Consumo Garantido": "12.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.12,
      "Preço CPQ 14%": 802932.68,
      "3% ACIMA": 808550,
      "VALOR FEIRA": 785000,
      "BORSO": 10000,
      "DESCONTO ": 0.12,
      "MARGEM": 0.0852,
      "BUYDOWN": 0.045
    }
  },
  {
    "id": 74,
    "codigo": "336-02BLN2.AA",
    "nome": "Escavadeira",
    "modelo": "336",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+336",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "LINHA MARTELO:  VALVULA E LINHA PARA MARTELO, PROTECAO COMPLETA ROLETES,BRACO 2,55M, LANCA 6,18M",
      "Contato com o solo": "CARRO INFERIOR ESTREITO, SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "37.500Kg",
      "Motor": "C7.1 300hp",
      "Ferramentas": "CAÇ 2,4M³ COM PROTETOR LATERAL",
      "Capacidade": "Profundidade max escav. 7.510mm ",
      "Consumo Garantido": "26.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.052,
      "Preço CPQ 14%": 1398135.58,
      "BUYDOWN": 0
    }
  },
  {
    "id": 75,
    "codigo": "350-05CLN3.AA",
    "nome": "Escavadeira",
    "modelo": "350",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+350",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "COM TECNOLOGIA: CABINE DELUXE, MONITOR 10\", LANÇA MASSA 6.55M, BRAÇO DE 2.5M, PROTEÇÃO COMPLETA DOS ROLETES, VENTILADOR REVERSÍVEL, CÂMERA 360, VÁLVULA E LINHA PARA MARTELO, BOMBA DE REABASTECIMENTO, LUZES NO CONTRAPESO, LUZES DE INSPEÇÃO",
      "Contato com o solo": "SAPATA DG DUPLA 600MM",
      "Peso Operacional": "47.600Kg",
      "Motor": "C9.3 B 414hp",
      "Ferramentas": "CAÇAMBA SD 3.21M3",
      "Capacidade": "Profundidade max escav. 8.240mm",
      "Consumo Garantido": "34.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 2024912.42,
      "BUYDOWN": 0
    }
  },
  {
    "id": 76,
    "codigo": "416-01ELN2.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES, DENTES, KEYPAD, PARALAMA,ESTAB. DE BORRACHA,PL",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 Turbo 96hp",
      "Ferramentas": "CACAMBA PADRAO INSTALADA",
      "Capacidade": "Profundidade max escav. 4.277mm",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 474143.3,
      "3% ACIMA": 453200,
      "VALOR FEIRA": 440000,
      "BORSO": 10000,
      "DESCONTO ": 0.113,
      "MARGEM": 0.0873,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 77,
    "codigo": "416-03CLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES + LINHAS, POWERSHIFT, DENTES, KEYPAD, PARALAMA,ESTAB. DE BORRACHA,PL, PROT. DO TANQUE, ENGATE RAPIDO.",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 Turbo 96hp",
      "Ferramentas": "CACAMBA PADRAO INSTALADA",
      "Capacidade": "Profundidade max escav. 4.277mm",
      "Consumo Garantido": "10.0 L/h",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 489418.72,
      "3% ACIMA": 499550,
      "VALOR FEIRA": 485000,
      "BORSO": 10000,
      "DESCONTO ": 0.113,
      "MARGEM": 0.1103,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 78,
    "codigo": "416-03DLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES + LINHAS, POWERSHIFT, DENTES, KEYPAD, PARALAMA,ESTAB. DE BORRACHA,PL, PROT. DO TANQUE, ENGATE RAPIDO.",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 Turbo 96hp",
      "Ferramentas": "CACAMBA PADRAO INSTALADA",
      "Capacidade": "Profundidade max escav. 4.277mm",
      "Consumo Garantido": "10.0 L/h",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 510823.76,
      "3% ACIMA": 499550,
      "VALOR FEIRA": 485000,
      "BORSO": 10000,
      "DESCONTO ": 0.113,
      "MARGEM": 0.1103,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 79,
    "codigo": "416-04DLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "MARTELO B8S, CABINE, 4X4, 5 FUNÇÕES + LINHAS, DENTES, KEYPAD, ENGATE RAPIDO MANUAL, PARALAMA,ESTAB. DE BORRACHA,PL",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 Turbo 96hp",
      "Ferramentas": "CACAMBA PADRAO INSTALADA",
      "Capacidade": "Profundidade max escav. 4.277mm",
      "Consumo Garantido": "10.0 L/h",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 535092.1,
      "BUYDOWN": 0
    }
  },
  {
    "id": 80,
    "codigo": "416-06DLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "06",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES, BORDA, BRAÇO EXTENSÍVEL, PARALAMA, ESTAB. DE BORRACHA, PL",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 Turbo 96hp",
      "Ferramentas": "CACAMBA PADRAO INSTALADA",
      "Capacidade": "Profundidade max escav. 4.277mm",
      "Consumo Garantido": "10.0 L/h",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 495901.03,
      "3% ACIMA": 478950,
      "VALOR FEIRA": 465000,
      "BORSO": 10000,
      "DESCONTO ": 0.113,
      "MARGEM": 0.097,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 81,
    "codigo": "920-02ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "ENGATE Rápido, REC. ELETR, PL, PROT DO A/C, VENTILADOR REVERSIVEL",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Peso Operacional": "9.132kg",
      "Motor": "Cat C4.4  102 hp",
      "Ferramentas": "CAÇ 1,9M³ (IT) BORDA",
      "Capacidade": "2.736Kg",
      "Consumo Garantido": "9,5l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 592918.92,
      "BUYDOWN": 0
    }
  },
  {
    "id": 82,
    "codigo": "920-03ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "ENGATE Rápido, REC. ELETR, PL, PROT DO A/C, VENTILADOR REVERSIVEL.",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Peso Operacional": "9.132kg",
      "Motor": "Cat C4.4  102 hp",
      "Ferramentas": "CAÇ 1,9M³ (IT) BORDA+ BIG BAG",
      "Capacidade": "2.736Kg",
      "Consumo Garantido": "9,5l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 609089.7,
      "BUYDOWN": 0
    }
  },
  {
    "id": 83,
    "codigo": "920-04ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "AGGREGATE: PNEU 20.5 R25, MI , CAÇ 2,0M(PO) BORDA, PROT A/C,  VENTILADOR REVERSIVEL, PL",
      "Contato com o solo": "PNEU 20.5 R25",
      "Peso Operacional": "9.132kg",
      "Motor": "Cat C4.4  102 hp",
      "Ferramentas": "CAÇ 2,0M(PO) BORDA",
      "Capacidade": "2.736Kg",
      "Consumo Garantido": "9,5l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 631290.83,
      "3% ACIMA": 633450,
      "VALOR FEIRA": 615000,
      "BORSO": 15000,
      "DESCONTO ": 0.115,
      "MARGEM": 0.1121,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 84,
    "codigo": "920-05LN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "MA ,ENGATE RAPIDO IT, PROT A/C, VENTILADOR REVERSIVEL, PL",
      "Contato com o solo": "PNEU 20.5 R25",
      "Peso Operacional": "9.132kg",
      "Motor": "Cat C4.4  102 hp",
      "Ferramentas": "CAÇ 1,9,0M BORDA",
      "Capacidade": "2.736Kg",
      "Consumo Garantido": "9,5l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 645125.06,
      "BUYDOWN": 0
    }
  },
  {
    "id": 85,
    "codigo": "924-04CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "MERCADO DE CONSTRUÇÃO: PNEU RADIAL 20.5R-25 MAXAM, CAÇAMBA 2.1M³ (PINADO) DENTES, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU RADIAL 20.5R-25 MAXAM",
      "Peso Operacional": "11.775 kg",
      "Motor": "Cat® C7.1*  141 hp",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Capacidade": "3.749,5 Kg",
      "Consumo Garantido": "15l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 763131.2,
      "3% ACIMA": 751900,
      "VALOR FEIRA": 730000,
      "BORSO": 15000,
      "DESCONTO ": 0.12300000000000001,
      "MARGEM": 0.102,
      "BUYDOWN": 0.025
    }
  },
  {
    "id": 86,
    "codigo": "924-05BLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "CONSTRUÇÃO RADIAL: PINADO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU RADIAL 20.5R25 MICHELIN",
      "Peso Operacional": "11.775 kg",
      "Motor": "Cat® C7.1*  141 hp",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Capacidade": "3.749,5 Kg",
      "Consumo Garantido": "15l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 804897.48,
      "BUYDOWN": 0
    }
  },
  {
    "id": 87,
    "codigo": "924-02CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "MERCADO AGRO:  Engate rápido FUSION, CONTRAPESO ADICIONAL, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU DIAGONAL 20.5-25 TITAN",
      "Peso Operacional": "11.775 kg",
      "Motor": "Cat® C7.1*  141 hp",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Capacidade": "3.749,5 Kg",
      "Consumo Garantido": "15l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 792790.97,
      "BUYDOWN": 0
    }
  },
  {
    "id": 88,
    "codigo": "924-01LN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CONTRUÇÃO 17.5 ENGATE: ENGATE RÁPIDO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 GOODYEAR",
      "Peso Operacional": "11.775 kg",
      "Motor": "Cat® C7.1*  141 hp",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Capacidade": "3.749,5 Kg",
      "Consumo Garantido": "15l/h",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 796290,
      "BUYDOWN": 0
    }
  },
  {
    "id": 89,
    "codigo": "966-02FLN3.AA",
    "nome": "Carregadeira",
    "modelo": "966",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+966",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " MINERIO DE FERRO, 2V COM RIDE CONTROL , EIXO ARREFECIDO, LUZES LED PREMIUM, VENTILADOR PADRÃO,  CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "23.790Kg",
      "Motor": "Cat® C9.3B 325 hp",
      "Ferramentas": "CAÇAMBA FERRO 2.80m³",
      "Capacidade": "8.230.4Kg",
      "Consumo Garantido": "20l/h",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1816161.76,
      "BUYDOWN": 0
    }
  },
  {
    "id": 90,
    "codigo": "707-01LN3.AA",
    "nome": "Fora de estrada",
    "modelo": "707",
    "familia": "Fora de estrada",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+707",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CAMINHÃO \"DUMPER\" CONCEBIDO PARA SER UTILIZADO FORA-DE-ESTRADA",
      "Motor": "C13",
      "Capacidade": "66T",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - India",
      "Familia": "AT",
      "Industria": "GCI",
      "BUYDOWN": 0
    }
  },
  {
    "id": 91,
    "codigo": "316GC-01DLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316GC",
    "detalhes": {
      "Configuração": "TERRAPLANAGEM ALCANCE SD: CABINE ROPS, BRACO 3.0M, LANCA 4,65M, CAÇ SD 0,65M³ (5 DENTES)",
      "3% ACIMA": 669500,
      "VALOR FEIRA": 650000,
      "BORSO": 10000,
      "DESCONTO ": 0.1,
      "MARGEM": 0.08220000000000001,
      "BUYDOWN": 0.045
    }
  }
];