const maquinasMock = [
  {
    "id": 1,
    "codigo": "120LVR-01PLN3.AA",
    "nome": "Motoniveladora",
    "modelo": "120 LVR",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+120%20LVR",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ALAVANCAS, TOP ADJUST, TELA TOUCH SCREEN, MEDIDOR DIGITAL DE INCLINAÇÃO DA LAMINA, LUZES EM LED",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "15.699Kg",
      "Motor": "C7.1 - 125hp",
      "Ferramentas": "LÂMINA DE 4,3M  , RIPPER C/ 5 DENTES",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1238383.5,
      "SPAR": 1188848.16
    }
  },
  {
    "id": 2,
    "codigo": "140GC-01GLN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 GC",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ALAVANCAS, LUZES HALÓGENAS",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "17.305Kg",
      "Motor": "C7.1 - 176hp",
      "Ferramentas": "LÂMINA DE 4,3M  , RIPPER C/ 5 DENTES E ESCARIFICADOR C/ 9 DENTES",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "17.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.11,
      "Preço CPQ 14%": 1119790.03,
      "SPAR": 1074998.4287999999
    }
  },
  {
    "id": 3,
    "codigo": "140JOY-02ELN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 JOY",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20JOY",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " 3D SEM MASTRO, CROSS SLOPE (2D), STABLE BLADE, AUTO-ARTICULAÇÃO, TOP ADJUST, LUZES EM LED",
      "Contato com o solo": "PNEU RADIAL 17.5 - 25",
      "Peso Operacional": "18.400Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "17.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.119,
      "Preço CPQ 14%": 1636055.44,
      "SPAR": 1570613.2223999999
    }
  },
  {
    "id": 4,
    "codigo": "140LVR3-01ALN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 LVR",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20LVR",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ALAVANCAS, MEDIDOR DIGITAL DE INCLINAÇÃO DA LAMINA, ACUMULADORES DE IMPACTO, LUZES HALÓGENAS",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "18.400Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1422911.88,
      "SPAR": 1365995.4048,
      "Opcionais": "Luz em Led, Tela Touch e Top Adjust",
      "Preço opcionais": 37000
    }
  },
  {
    "id": 5,
    "codigo": "150JOY-01ELN3.AA",
    "nome": "Motoniveladora",
    "modelo": "150 JOY",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+150%20JOY",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " JOY, CROSS SLOPE (2D), STABLE BLADE, AUTO-ARTICULAÇÃO, TOP ADJUST, LUZES EM LED",
      "Contato com o solo": "PNEU RADIAL 17.5R25",
      "Peso Operacional": "18.991Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1687877.88,
      "SPAR": 1620362.7647999998
    }
  },
  {
    "id": 6,
    "codigo": "160JOY-01DLN3.AA",
    "nome": "Motoniveladora",
    "modelo": "160 JOY",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+160%20JOY",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "LUZ DE LED, ARO + CROSS SLOPE + STABLE BLADE + CONTROLE AUTOMÁTICO DE ARTICULAÇÃO",
      "Contato com o solo": "PNEUS 17.5R25 MICHELIM",
      "Peso Operacional": "20.607Kg",
      "Motor": "C9 - 213hp",
      "Ferramentas": "LÂMINA DE 4,3M PLUS, RIPPER/ESCARIFICADOR C/ 9 DENTES",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "22.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1771111.94,
      "SPAR": 1700267.4623999998
    }
  },
  {
    "id": 7,
    "codigo": "226B3-01PDC.AA",
    "nome": "Minicarregadeira",
    "modelo": "226 B3",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+226%20B3",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "JOYSTICK PILOTADO, CABINE COM AR",
      "Contato com o solo": "Pneu ",
      "Peso Operacional": "2.641Kg",
      "Motor": "C2.2T - 56hp",
      "Ferramentas": "CACAMBA 1730MM E 0,40 M³, BORDA",
      "Capacidade": "Carga max levantamento 680Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 336883.64,
      "SPAR": 323408.2944
    }
  },
  {
    "id": 8,
    "codigo": "250-03BLN2.AA",
    "nome": "Minicarregadeira",
    "modelo": "250",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+250",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "FLUXO PADRÃO (STANDARD FLOW), JOYSTICK ELETRONICO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, 1 VELOCIDADE,  ASSENTO VINIL, SEM CONTRAPESO",
      "Contato com o solo": "PNEU 10/16,5",
      "Peso Operacional": "3.551Kg",
      "Motor": "C2.8T - 74hp",
      "Ferramentas": "CACAMBA 1883MM",
      "Capacidade": "Carga max levantamento 1.220Kg",
      "Consumo Garantido": "5.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 370295.28,
      "SPAR": 355483.46880000003,
      "Opcionais": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS), JOYSTICK AVANÇADO, MONITOR AVANÇADO, 2 VELOCIDADES, ASSENTO TECIDO, CONTRAPESO ADICIONAL",
      "Preço opcionais": 25500
    }
  },
  {
    "id": 9,
    "codigo": "260-02ALN3.AA",
    "nome": "Minicarregadeira",
    "modelo": "260",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+260",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS,  JOYSTICK AVANÇADO, MONITOR AVANÇADO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, 2 VELOCIDADES, ASSENTO TECIDO,CONTRAPESO ADICIONAL",
      "Contato com o solo": " PNEU 12/16,5",
      "Peso Operacional": "3.866Kg",
      "Motor": "C2.8T - 74hp",
      "Ferramentas": "CACAMBA 2036MM",
      "Capacidade": "Carga max levantamento1.540Kg",
      "Consumo Garantido": "6.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 438417.45,
      "SPAR": 420880.752
    }
  },
  {
    "id": 10,
    "codigo": "270-01LN3.AA",
    "nome": "Minicarregadeira",
    "modelo": "270",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+270",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS,  JOYSTICK AVANÇADO, MONITOR AVANÇADO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, CAMERAS LATERAIS, 2 VELOCIDADES,  CONTRAPESO",
      "Contato com o solo": "PNEU 14/17,5",
      "Peso Operacional": "4.736Kg",
      "Motor": "C3.6T - 100hp",
      "Ferramentas": "CAÇAMBA 2184mm 0,63M³ E 9 DENTES",
      "Capacidade": "Carga max levantamento1.776Kg",
      "Consumo Garantido": "6.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 522045.68,
      "SPAR": 501163.8528
    }
  },
  {
    "id": 11,
    "codigo": "302.7-03APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "302.7",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+302.7",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE ABERTA REBATÍVEL",
      "Contato com o solo": "ESTEIRA DE AÇO",
      "Peso Operacional": "2.925Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,08M³ E 460MM",
      "Capacidade": "Profundidade max escav. 2.710mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.14,
      "Preço CPQ 14%": 274265.87,
      "SPAR": 263295.2352,
      "Opcionais": "Cabine fechada com ar condicionado, esteira de aço ou borracha",
      "Preço opcionais": 25000
    }
  },
  {
    "id": 12,
    "codigo": "303.5-02APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "303.5",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+303.5",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CABINE FECHADA, ENGATE RAPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REVATÍVEL",
      "Contato com o solo": "ESTEIRA DE BORRACHA",
      "Peso Operacional": "4.190Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,12M³ E 619MM",
      "Capacidade": "Profundidade max escav. 3.110mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.095,
      "Preço CPQ 14%": 338458.57,
      "SPAR": 324920.2272,
      "Opcionais": "Esteira de aço",
      "Preço opcionais": 5900
    }
  },
  {
    "id": 13,
    "codigo": "307-01ALN3.AA",
    "nome": "Miniescavadeira",
    "modelo": "307",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+307",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " CABINE FECHADA E AR CONDIOCIONADO",
      "Contato com o solo": "ESTEIRAS DE AÇO",
      "Peso Operacional": "7.500Kg",
      "Motor": "C2.4T - 49hp",
      "Ferramentas": "CAÇAMBA DE 0,33M³ E LARGURA DE 854MM",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "MHEX",
      "Industria": "BCP",
      "SPAR": 0
    }
  },
  {
    "id": 14,
    "codigo": "313GC-01DLN2.AA",
    "nome": "Escavadeira",
    "modelo": "313 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+313%20GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE ROPS, BRACO 2,5M, LANCA 4,65M, PROTEÇÃO DO SWIVEL",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "12.400Kg",
      "Motor": "C3.6 - 95hp",
      "Ferramentas": "CAÇAMBA GD 0,53M³",
      "Capacidade": "Profundidade max escav. 5.570mm ",
      "Consumo Garantido": "9.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 589014.02,
      "SPAR": 565453.4592
    }
  },
  {
    "id": 15,
    "codigo": "316GC-03FLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316%20GC",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE ROPS, BRACO 2.5M HD, LANCA 4,65M",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "14.600Kg",
      "Motor": "C3.6 - 104hp",
      "Ferramentas": "CAÇ SD 0,65M³ (5 DENTES)",
      "Capacidade": "Profundidade max escav. 5.530mm ",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 688013.41,
      "SPAR": 660492.8736,
      "Opcionais": "Braço 3,0m e Valvula aux com linha",
      "Preço opcionais": 4400
    }
  },
  {
    "id": 16,
    "codigo": "318GC-01BLN2.AA",
    "nome": "Escavadeira",
    "modelo": "318GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+318GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE ROPS, VALVULA AUXILIAR MARTELO SEM LINHA, BRACO 2,6M, LANCA 5,1M",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Peso Operacional": "17.500Kg",
      "Motor": "C3.6 - 111hp",
      "Ferramentas": "CAÇ SD 0,91M",
      "Capacidade": "Profundidade max escav. 6.110mm ",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 745471.73,
      "SPAR": 715652.8607999999,
      "Opcionais": "Valvula 2 sentidos e linha hidraulica aux",
      "Preço opcionais": 30000
    }
  },
  {
    "id": 17,
    "codigo": "320-01ULN3.AA",
    "nome": "Escavadeira",
    "modelo": "320",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "VALVULA AUXILIAR, BRACO HD 2,9M, LANCA HD 5,7M",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Peso Operacional": "21.300Kg",
      "Motor": "C7.1 - 157hp",
      "Ferramentas": "CAÇ HD 1,4M³",
      "Capacidade": "Profundidade max escav. 6.720mm ",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 893506.86,
      "SPAR": 857766.5856,
      "Opcionais": "VALVULA AUXILIAR (2 SENTIDOS) + LINHA",
      "Preço opcionais": 25700
    }
  },
  {
    "id": 18,
    "codigo": "320GC-01RLN2.AA",
    "nome": "Escavadeira",
    "modelo": "320 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320%20GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "VALVULA AUXILIAR MARTELO SEM LINHA, BRACO 2,9M, LANCA 5,7M",
      "Contato com o solo": "CARRO MÉDIO",
      "Peso Operacional": "20.400Kg",
      "Motor": "C4.4 - 143hp",
      "Ferramentas": "CAÇ GD 1,16M³",
      "Capacidade": "Profundidade max escav. 6.630mm ",
      "Consumo Garantido": "12.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 784212.58,
      "SPAR": 752844.0767999999,
      "Opcionais": "Linha hidraulica aux",
      "Preço opcionais": 18700
    }
  },
  {
    "id": 19,
    "codigo": "323-01QLN2.AA",
    "nome": "Escavadeira",
    "modelo": "323",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+323",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "VALVULA AUXILIAR, BRACO HD 2,5M, LANCA HD 5,7M",
      "Contato com o solo": "SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "22.900Kg",
      "Motor": "C7.1 - 157hp",
      "Ferramentas": "CAÇ HD 1,56M³",
      "Capacidade": "Profundidade max escav. 6.730mm ",
      "Consumo Garantido": "17.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 962613.54,
      "SPAR": 924108.9984
    }
  },
  {
    "id": 20,
    "codigo": "336-01HLN2.AA",
    "nome": "Escavadeira",
    "modelo": "336",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+336",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PROTECAO COMPLETA ROLETES, BRACO 2,55M, LANCA 6,18M",
      "Contato com o solo": "CARRO INFERIOR ESTREITO, SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "37.500Kg",
      "Motor": "C7.1 TTA - 306hp",
      "Ferramentas": "CAÇ 2,4M³ COM PROTETOR LATERAL",
      "Capacidade": "Profundidade max escav. 7.510mm ",
      "Consumo Garantido": "26.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 1364832.22,
      "SPAR": 1310238.9312,
      "Opcionais": "VALVULA E LINHA PARA MARTELO",
      "Preço opcionais": 33000
    }
  },
  {
    "id": 21,
    "codigo": "340-01BLN3.AA",
    "nome": "Escavadeira",
    "modelo": "340",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+340",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PEDREIRA/MINERAÇÃO: VENTILADOR REVERSÍVEL, PROTECAO COMPLETA ROLETES,BRACO 2,55M, LANCA 6,18M",
      "Contato com o solo": "SAPATA GARRA DUPLA 600MM",
      "Peso Operacional": "36.800Kg",
      "Motor": "C9.3B - 346hp",
      "Ferramentas": "CAÇ 2,6M³ COM PROTETOR LATERAL",
      "Capacidade": "Profundidade max escav. 7.480mm ",
      "Consumo Garantido": "28.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 1610725.98,
      "SPAR": 1546296.9408
    }
  },
  {
    "id": 22,
    "codigo": "350-04CLN3.AA",
    "nome": "Escavadeira",
    "modelo": "350",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+350",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "SEM TECNOLOGIA: CABINE DELUXE, MONITOR 10\", LANÇA MASSA 6,55M, BRAÇO DE 2.5M, PROTEÇÃO COMPLETA DOS ROLETES, VENTILADOR REVERSÍVEL, CÂMERA TRASEIRA, VÁLVULA PARA MARTELO",
      "Contato com o solo": "SAPATA DG 600MM",
      "Peso Operacional": "47.600Kg",
      "Motor": "C9.3B - 420hp",
      "Ferramentas": "CAÇAMBA SD 3.21M3",
      "Capacidade": "Profundidade max escav. 7.690mm ",
      "Consumo Garantido": "34.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 1941370.92,
      "SPAR": 1863716.0831999998,
      "Opcionais": "Tecnologia de corte + CÂMERA 360, LINHA PARA MARTELO, BOMBA DE REABASTECIMENTO, LUZES NO CONTRAPESO, LUZES DE INSPEÇÃO, Sapata dupla",
      "Preço opcionais": 330000
    }
  },
  {
    "id": 23,
    "codigo": "416-02CLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "CABINE, 4X4, 4 FUNÇÕES, DENTES,PL",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 - 87hp",
      "Ferramentas": "Caçamba GP 1,0m³ e 0,23m³",
      "Capacidade": "Profundidade escav. 4.277mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 465433.42,
      "SPAR": 446816.0832,
      "Opcionais": " 1 FUNÇÃO Extra, KEYPAD, PARALAMA,ESTAB. DE BORRACHA",
      "Preço opcionais": 8700,
      "Opcionais_1": " 1 FUNÇÃO Extra + Linha, KEYPAD, PARALAMA,ESTAB. DE BORRACHA",
      "Preço opcionais_1": 23900,
      "Opcionais_2": " 1 FUNÇÃO Extra + Linha, POWERSHIFT, PROT. DO TANQUE, ENGATE RAPIDO.",
      "Preço opcionais_2": 45300,
      "Opcionais_3": "MARTELO B8S, 1 FUNÇÃO Extra + Linha, KEYPAD, PARALAMA,ESTAB. DE BORRACHA",
      "Preço opcionais_3": 69600,
      "Opcionais_4": "5 FUNÇÕES,  BRAÇO EXTENSÍVEL, PARALAMA, ESTAB. DE BORRACHA",
      "Preço opcionais_4": 30400
    }
  },
  {
    "id": 24,
    "codigo": "420-01CLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "420",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+420",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES, DENTE, ESTAB. DE BORRACHA, PARALAMA, KEYPAD, PL",
      "Contato com o solo": "Pneus Goodyear",
      "Peso Operacional": "11.000Kg",
      "Motor": "C4.4 - 94hp",
      "Ferramentas": "Caçamba GP 1,0m³ e 0,23m132",
      "Capacidade": "Profundidade escav. 4.278mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 504558.49,
      "SPAR": 484376.1504
    }
  },
  {
    "id": 25,
    "codigo": "914-01LN3.AA",
    "nome": "Carregadeira",
    "modelo": "914",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+914",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PCT DE RECURSOS, CARREG, FILTRO DETRITOS COND. , VENTILADOR REVERSIVEL, PL, PROT A/C",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Peso Operacional": "8.568Kg",
      "Motor": "C4.4 - 100hp",
      "Ferramentas": "CAÇ 1,6M³ (PO) BORDA",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 511439.34,
      "SPAR": 490981.7664
    }
  },
  {
    "id": 26,
    "codigo": "920-01ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "REC. ELETR, PL, PROT DO A/C, VENTILADOR REVERSIVEL",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Peso Operacional": "9.132Kg",
      "Motor": "C4.4 - 100hp",
      "Ferramentas": "CAÇ 1,9M³ (PO) BORDA",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 584303.08,
      "SPAR": 560930.9567999999,
      "Opcionais": "Engate Rápido IT",
      "Preço opcionais": 72800,
      "Opcionais_1": "Pneu Michelin 20,5",
      "Preço opcionais_1": 46900,
      "Opcionais_2": "Engate rápido e Pneu Michelin 20,5",
      "Preço opcionais_2": 60800
    }
  },
  {
    "id": 27,
    "codigo": "924-03CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "MERCADO GERAL: PINADO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 TITAN",
      "Peso Operacional": "11.775Kg",
      "Motor": "C7.1 - 137hp",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 746508.86,
      "SPAR": 716648.5055999999,
      "Opcionais": "PNEU RADIAL 20.5R-25 MAXAM",
      "Preço opcionais": 16600,
      "Opcionais_1": "PNEU RADIAL 20.5R25 MICHELIN",
      "Preço opcionais_1": 58300,
      "Opcionais_2": "Engate rápido FUSION, CONTRAPESO ADICIONAL, PNEU DIAGONAL 20.5-25 TITAN",
      "Preço opcionais_2": 46000,
      "Opcionais_3": "ENGATE: ENGATE RÁPIDO, PNEU DIAGONAL 17.5-25 GOODYEAR",
      "Preço opcionais_3": 49700
    }
  },
  {
    "id": 28,
    "codigo": "930-01ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "930",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+930",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PINADO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO).",
      "Contato com o solo": "PNEU RADIAL 20.5R-25 MAXAM",
      "Peso Operacional": "13.246Kg",
      "Motor": "C7.1 - 160hp",
      "Ferramentas": "CAÇAMBA 2.5M³, DENTES",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.121,
      "Preço CPQ 14%": 920568.2,
      "SPAR": 883745.472
    }
  },
  {
    "id": 29,
    "codigo": "938-01ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "938",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+938",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CANA-DE-AÇÚCAR BAGAÇO VOLANTE: VOLANTE, MONITOR 8\", CÂMERA DE RÉ, HÉLICE REVERSÍVEL, FARÓIS LED, PRODUCT LINK DUAL (HÍBRIDO), ASSENTO PREMIUM, GIROFLEX.",
      "Contato com o solo": "PNEU AGRÍCOLA 750/65R26 MICHELIN",
      "Peso Operacional": "15.399Kg",
      "Motor": "C7.1 - 188hp",
      "Ferramentas": "CAÇAMBA BAGAÇO 6.0M³ (PO) BORDAS",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.086,
      "Preço CPQ 14%": 1117274.89,
      "SPAR": 1072583.8943999999
    }
  },
  {
    "id": 30,
    "codigo": "938-04BLN2.AA",
    "nome": "Carregadeira",
    "modelo": "938",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+938",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "CONTRUÇÃO: PINADO, VENTILADOR REVERSÍVEL, MONITOR 8\", CÂMERA DE RÉ, ASSENTO COM SENSOR DE PRESENÇA, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU RADIAL 20.5R25 MICHELIN",
      "Peso Operacional": "15.399Kg",
      "Motor": "C7.1 - 188hp",
      "Ferramentas": "CAÇAMBA 2.7M³, DENTES",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.086,
      "Preço CPQ 14%": 1104638.82,
      "SPAR": 1060453.2672000001
    }
  },
  {
    "id": 31,
    "codigo": "950-01CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "950",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+950",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ROCHA, 2V SEM RIDE CONTROL , EIXO ARREFECIDO, LUZES HALÓGENAS PREMIUM, VENTILADOR PADRÃO, PRÉ-PURIFICADOR TURBINA, CONTRAPESO AUXILIAR",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "18.076Kg",
      "Motor": "C7.1 - 253hp",
      "Ferramentas": "CAÇAMBA ROCHA 2.90m³",
      "Consumo Garantido": "15.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1468290.84,
      "SPAR": 1409559.2064
    }
  },
  {
    "id": 32,
    "codigo": "950GC-01HLN2.AA",
    "nome": "Carregadeira",
    "modelo": "950GC",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+950GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " PAYLOAD, EIXO ARREFECIDO, 2V SEM RIDE CONTROL, 04 LUZES HALÓGENAS, VENTILADOR REVERSÍVEL, PRÉ-PURIFICADOR TURBINA, CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEUS L3",
      "Peso Operacional": "18.676Kg",
      "Motor": "C7.1 - 202hp",
      "Ferramentas": "CAÇAMBA GP 3.40m³",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1095369.5,
      "SPAR": 1051554.72
    }
  },
  {
    "id": 33,
    "codigo": "962-01CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "962",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+962",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ROCHA: EIXO ARREFECIDO, CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEU 23.5R25 L5 MICHELIM",
      "Peso Operacional": "19.043Kg",
      "Motor": "C7.1 - 273hp",
      "Ferramentas": "CAÇ ROCHA 3,1M³ (PO)",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1524307.28,
      "SPAR": 1463334.9888
    }
  },
  {
    "id": 34,
    "codigo": "966-01ELN3.AA",
    "nome": "Carregadeira",
    "modelo": "966",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+966",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ROCHA, 2V SEM RIDE CONTROL , EIXO ARREFECIDO, LUZES HALÓGENAS PREMIUM, VENTILADOR PADRÃO,  CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "23.196Kg",
      "Motor": "C9.3B - 325hp",
      "Ferramentas": "CAÇAMBA ROCHA 3.40m³",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1793392.4,
      "SPAR": 1721656.704
    }
  },
  {
    "id": 35,
    "codigo": "972-02ILN3.AA",
    "nome": "Carregadeira",
    "modelo": "972",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+972",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CERAMICA/AGREGADO, 2V COM RIDE CONTROL, CAMERA TRASEIRA, EIXO ARREFECIDO, CONTRAPESO AGREGADO, VENTILADOR REVERSÍVEL, LUZES HALÓGENAS PREMIUM, PAYLOAD ADVANCED, AUTOLUBE",
      "Contato com o solo": "PNEUS L3",
      "Peso Operacional": "24.890Kg",
      "Motor": "C9.3B - 344hp",
      "Ferramentas": "CAÇAMBA GP 5.30m³",
      "Consumo Garantido": "20.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1910860.47,
      "SPAR": 1834426.0511999999
    }
  },
  {
    "id": 36,
    "codigo": "980-02ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "980",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+980",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " MINERIO DE FERRO, 2V COM RIDE CONTROL, EIXO ARREFECIDO, LUZES LED PREMIUM, VENTILADOR PADRÃO, PRÉ-PURIFICADOR TURBINA, CAT DETECT, CONTRAPESO AGREGADO",
      "Contato com o solo": "PNEUS L5",
      "Peso Operacional": "30.344Kg",
      "Motor": "C13 - 417hp",
      "Ferramentas": "CAÇAMBA IRON 3,80m³",
      "Consumo Garantido": "27.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 2755824.79,
      "SPAR": 2645591.7983999997
    }
  },
  {
    "id": 37,
    "codigo": "CB10-01DLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB10",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB10",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, SENSOR DE TEMPERATURA, 5 AMPLITUDES E 1 FREQUENCIA",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "9.500Kg",
      "Motor": "C4.4 - 131,8hp",
      "Ferramentas": "1700mm (0,18mm e 0,84mm)",
      "Capacidade": "Peso Max 10.510Kg",
      "Consumo Garantido": "6.5 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.088,
      "Preço CPQ 14%": 698765.22,
      "SPAR": 670814.6111999999
    }
  },
  {
    "id": 38,
    "codigo": "CB2_5GC-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB2.5",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB2.5",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ROPS, 2 AJUSTES DE FREQUENCIA DE 62 E 50HZ",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "2.521Kg",
      "Motor": "C1.7T - 24,7hp",
      "Ferramentas": "1000mm x 720mm (0,51mm)",
      "Capacidade": "Peso Max 3.021Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.068,
      "SPAR": 0
    }
  },
  {
    "id": 39,
    "codigo": "CB2_7GC-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB2.7",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB2.7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ROPS, 2 AJUSTES DE FREQUENCIA DE 62 E 50HZ",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "2.698Kg",
      "Motor": "C1.7T - 24,7hp",
      "Ferramentas": "1200mm x 720mm (0,52mm)",
      "Capacidade": "Peso Max 3.198Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.068,
      "SPAR": 0
    }
  },
  {
    "id": 40,
    "codigo": "CB7-01DLN2.AA",
    "nome": "Rolo Compactador",
    "modelo": "CB7",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CB7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, SENSOR DE TEMPERATURA, 2 AMPLITUDES E 2 FREQUENCIAS",
      "Contato com o solo": "Chapa - Chapa",
      "Peso Operacional": "7.990Kg",
      "Motor": "C2.2 - 49,1hp",
      "Ferramentas": "1500mm (",
      "Capacidade": "Peso Max 8.940Kg",
      "Consumo Garantido": "6.5 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.088,
      "Preço CPQ 14%": 645092.97,
      "SPAR": 619289.2511999999
    }
  },
  {
    "id": 41,
    "codigo": "CC4_0-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CC4.0",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CC4.0",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "2 AJUSTES DE FREQUÊNCIA DE 55 E 48HZ",
      "Contato com o solo": "Chapa - Pneu",
      "Peso Operacional": "3.378Kg",
      "Motor": "C2.2 - 49,1hp",
      "Ferramentas": "800mm (0,5mm)",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.068,
      "SPAR": 0
    }
  },
  {
    "id": 42,
    "codigo": "CP11-02LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CP11",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CP11",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CABINE,MDP",
      "Contato com o solo": "Patas",
      "Peso Operacional": "11.383Kg",
      "Motor": "C4.4 - 130hp",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 747147.08,
      "SPAR": 717261.1967999999
    }
  },
  {
    "id": 43,
    "codigo": "CP11GC-02ELN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CP11GC",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CP11GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " CABINE PREMIUM, MDP, ASSENTO DE TECIDO",
      "Contato com o solo": "Patas",
      "Peso Operacional": "11.387Kg",
      "Motor": "C4.4 - 112hp",
      "Ferramentas": "2134mm x 1549mm",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 654496.76,
      "SPAR": 628316.8896
    }
  },
  {
    "id": 44,
    "codigo": "CS10GC-01FLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS10GC",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS10GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " CABINE PREMIUM, KIT PATAS, MDP, ASSENTO DE TECIDO",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "10.492Kg",
      "Motor": "C4.4 - 112hp",
      "Ferramentas": "2134mm x 1535mm",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "ACOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 622646.33,
      "SPAR": 597740.4768
    }
  },
  {
    "id": 45,
    "codigo": "CS11-04ALN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS11",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS11",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": " CABINE, KIT PATAS, MDP",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "10.806Kg",
      "Motor": "C4.4 - 130hp",
      "Ferramentas": "2134mm x 1535mm",
      "Consumo Garantido": "13.5 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 748578.73,
      "SPAR": 718635.5808
    }
  },
  {
    "id": 46,
    "codigo": "CS11GC-01GLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS11GC",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS11GC",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " CABINE PREMIUM, KIT PATAS, MDP, ASSENTO DE TECIDO",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "11.235Kg",
      "Motor": "C4.4 - 112hp",
      "Ferramentas": "2134mm x 1535mm",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 659264.12,
      "SPAR": 632893.5552
    }
  },
  {
    "id": 47,
    "codigo": "CS20-01LN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS20",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS20",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "AMPLITUDE ALTA DE 2,1MM E AMPLITUDE BAIXA DE 0,98MM.",
      "Contato com o solo": "Patas",
      "Peso Operacional": "20.220Kg",
      "Motor": "C7.1 - 173hp",
      "Ferramentas": "2134mm x 1535mm",
      "Consumo Garantido": "18.5 L/h",
      "Fabricação": "Importado",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "SPAR": 0
    }
  },
  {
    "id": 48,
    "codigo": "CS7-03BLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CS7",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CS7",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE, KIT PATAS, SEM MDP",
      "Contato com o solo": "Chapa",
      "Peso Operacional": "7.210Kg",
      "Motor": "C4.4 - 131hp",
      "Ferramentas": "1676mm x 1221mm",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "SCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 485106.28,
      "SPAR": 465702.02880000003
    }
  },
  {
    "id": 49,
    "codigo": "CW34-01HLN3.AA",
    "nome": "Rolo Compactador",
    "modelo": "CW34",
    "familia": "Rolo Compactador",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+CW34",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "27.000Kg",
      "Motor": "C4.4 - 100hp",
      "Ferramentas": "2090mm",
      "Consumo Garantido": "6.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "PCOM",
      "Industria": "PAV",
      "Desconto Vigente PSC": 0.103,
      "Preço CPQ 14%": 797908.14,
      "SPAR": 765991.8144
    }
  },
  {
    "id": 50,
    "codigo": "D4-01ELN2.AA",
    "nome": "Trator Esteiras",
    "modelo": "D4",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D4",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "GRADE 2D, CÂMERA DE RÉ, PRÉ- PURIFICADOR TURBINA, VENTILADOR REVERSÍVEL, LUZES EM LED",
      "Contato com o solo": "SAPATA DE 560mm",
      "Peso Operacional": "13.500Kg",
      "Motor": "C7.1 - 130hp",
      "Ferramentas": "LÂMINA VPAT DE 3.3m³, RIPPER COM 3 DENTES",
      "Consumo Garantido": "14.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1128748.12,
      "SPAR": 1083598.1952
    }
  },
  {
    "id": 51,
    "codigo": "D5-01JLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D5",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D5",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PRÉ-PURIFICADOR TURBINA, TELA TOUCHSCRREN 10\", COM TECNOLOGIA 2D, 06 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": "SAPATA 560MM ES HDXL CTWS",
      "Peso Operacional": "19.070Kg",
      "Motor": "C7.1 - 170hp",
      "Ferramentas": "LÂMINA VPAT DE 3.3m³, RIPPER COM 3 DENTES",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1460542.41,
      "SPAR": 1402120.7136
    }
  },
  {
    "id": 52,
    "codigo": "D5-08CLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D5",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D5",
    "detalhes": {
      "Arranjo": "08",
      "Configuração": "FINE GRADING, PRÉ- PURIFICADOR TURBINA, TELA TOUCHSCRREN 10\", COM TECNOLOGIA 2D, 06 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": " SAPATA 600MM ES HDXL CTWS",
      "Peso Operacional": "19.070Kg",
      "Motor": "C7.1 - 170hp",
      "Ferramentas": "LÂMINA VPAT 4.0M³, RIPPER COM 3 DENTES",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.113,
      "Preço CPQ 14%": 1448725.19,
      "SPAR": 1390776.1823999998
    }
  },
  {
    "id": 53,
    "codigo": "D6-01BLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D6",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D6",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "TELA TOUCHSCREEN 10\", SEM TECNOLOGIA, CAMERA TRASEIRA, 06 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": "ESTEIRA 560MM ES HDXL",
      "Peso Operacional": "22.130Kg",
      "Motor": "C9.3B - 215hp",
      "Ferramentas": "LÂMINA SU, RIPPER 3 DENTES",
      "Consumo Garantido": "25.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1907203.65,
      "SPAR": 1830915.504
    }
  },
  {
    "id": 54,
    "codigo": "D7-01CLN3ARO.AA",
    "nome": "Trator Esteiras",
    "modelo": "D7",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "PRÉ- PURIFICADOR TURBINA, TROCA DE ÓLEO RÁPIDA, TELA TOUCHSCREEN 10\", CAMERA TRASEIRA, 12 LUZES EM LED, VENTILADOR REVERSÍVEL",
      "Contato com o solo": " ESTEIRA 560MM ES HD CTWS",
      "Peso Operacional": "29.776Kg",
      "Motor": "C9.3B - 265hp",
      "Ferramentas": "LÂMINA SU, RIPPER 3 DENTES",
      "Consumo Garantido": "32.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 2934133.03,
      "SPAR": 2816767.7087999997
    }
  },
  {
    "id": 55,
    "codigo": "D8-02CLN3.AA",
    "nome": "Trator Esteiras",
    "modelo": "D8",
    "familia": "Trator Esteiras",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+D8",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "SINGLE TILT, PRÉ-PURIFICADOR TURBINA, TROCA DE ÓLEO RÁPIDA, VENTILADOR REVERSÍVEL, TELA TOUCHSCREEN 10\", COM GRADE 2D, CAMERA TRASEIRA, 12 LUZES EM LED",
      "Contato com o solo": "ESTEIRA 610MM ES HD CTWS",
      "Peso Operacional": "39.000Kg",
      "Motor": "C15 - 363hp",
      "Ferramentas": "LÂMINA SU, RIPPER UNIDENTE COM SACO PINO",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "TTTMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 3851645.03,
      "SPAR": 3697579.2287999997
    }
  },
  {
    "id": 56,
    "codigo": "MH3032-01LN3.AA",
    "nome": "Manipulador Hidraulico",
    "modelo": "MH3032",
    "familia": "Manipulador Hidraulico",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+MH3032",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "ALCANCE MÁXIMO DE CARREGAMENTO DE 14.840 MM, ALTURA MÁXIMA DE 16.270 MM",
      "Contato com o solo": "Pneus duplado",
      "Peso Operacional": "34.500Kg",
      "Motor": "C7.1 - 212hp",
      "Ferramentas": "Garra ",
      "Consumo Garantido": "-",
      "Fabricação": "Importado",
      "Familia": "WHEX",
      "Industria": "GCI",
      "SPAR": 0
    }
  },
  {
    "id": 57,
    "codigo": "SEM618D-03.SM",
    "nome": "Carregadeira",
    "modelo": "SEM618D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM618D",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "TRANSMISSAO ZL15, EIXO ZL16, ENGATE RAPIDO COM PINO HORIZONTAL, 3a VALVULA E AR CONDICIONADO",
      "Contato com o solo": "Pneus",
      "Motor": "YTO 4.7 - 84hp",
      "Ferramentas": "CACAMBA DE 1.0M3 e  GARFO PALLET",
      "Capacidade": "1.800Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "SPAR": 0
    }
  },
  {
    "id": 58,
    "codigo": "SEM618D-05.SM",
    "nome": "Carregadeira",
    "modelo": "SEM618D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM618D",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "TRANSMISSÃO ZL15, EIXO ZL16.",
      "Contato com o solo": "Pneus",
      "Motor": "YTO 4.7 - 84hp",
      "Ferramentas": "CACAMBA DE 1.0M3",
      "Capacidade": "1.800Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "SPAR": 0
    }
  },
  {
    "id": 59,
    "codigo": "SEM636D-07PLA.SM",
    "nome": "Carregadeira",
    "modelo": "SEM636D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM636D",
    "detalhes": {
      "Arranjo": "07",
      "Configuração": "PINADA, TRANSMISSAO SEM E AR CONDICIONADO",
      "Contato com o solo": "Pneus",
      "Motor": "WEICHAI",
      "Ferramentas": "CACAMBA DE 1,7M3",
      "Capacidade": "3.000Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "SPAR": 0
    }
  },
  {
    "id": 60,
    "codigo": "SEM636D-08PL.SM",
    "nome": "Carregadeira",
    "modelo": "SEM636D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM636D",
    "detalhes": {
      "Arranjo": "08",
      "Configuração": "ENGATE RAPIDO-QC, TRANSMISSAO SEM, 2a.VALVULA E AR CONDICIONADO",
      "Contato com o solo": "Pneus",
      "Motor": "WEICHAI",
      "Ferramentas": "CACAMBA DE 1,7M4",
      "Capacidade": "3.000Kg",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "SPAR": 0
    }
  },
  {
    "id": 61,
    "codigo": "SEM656D-03B.SM",
    "nome": "Carregadeira",
    "modelo": "SEM656D",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM656D",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "TRANSMISSAO SEM TR200 F4/R4, 2a. VALVULA E AR CONDICIONADO.",
      "Contato com o solo": "Pneus",
      "Peso Operacional": "17.000Kg",
      "Motor": "WEICHAI 9.7 - 206hp",
      "Ferramentas": "CACAMBA 3M3 PS",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "CWL",
      "Industria": "BCP",
      "SPAR": 0
    }
  },
  {
    "id": 62,
    "codigo": "SEM915F-02.SM",
    "nome": "Motoniveladora",
    "modelo": "SEM915F",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM915F",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "CABINE STD, TRANSMISSÃO HANGCHI 6YD13 TIPO POWERSHIFT, PREPARACAO PARA EMPLACAMENTO",
      "Contato com o solo": "PNEUS 14.0-24 TL12PR L2",
      "Motor": "SDEC - 165hp",
      "Ferramentas": "LÂMINA DE 3.7M, RIPPER TRASEIRO COM 3 DENTES",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "MG",
      "Industria": "GCI",
      "SPAR": 0
    }
  },
  {
    "id": 63,
    "codigo": "SEM919BRZ-01APLB.SM",
    "nome": "Motoniveladora",
    "modelo": "SEM919",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+SEM919",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "STANDARD CAB, ALTURA MAXIMA DE LEVANTAMENTO DA LAMINA DE 715 MM, TRANSMISSAO HANGCHI 6WG 180 AUTOMATICA, PREPARACAO PARA EMPLACAMENTO, EIXO ST23",
      "Contato com o solo": "Pneus",
      "Motor": "PERKINS 7.0 - ",
      "Ferramentas": "RIPPER TRASEIRO COM 3 DENTES",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - China",
      "Familia": "MG",
      "Industria": "GCI",
      "SPAR": 0
    }
  },
  {
    "id": 64,
    "codigo": "140-01LN3.AA",
    "nome": "Motoniveladora",
    "modelo": "140 LVR",
    "familia": "Motoniveladora",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+140%20LVR",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " ALAVANCAS, TOP ADJUST, TELA TOUCH SCREEN, MEDIDOR DIGITAL DE INCLINAÇÃO DA LAMINA, ACUMULADORES DE IMPACTO, LUZES EM LED",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 16 LONAS",
      "Peso Operacional": "18.400Kg",
      "Motor": "C7.1 - 183hp",
      "Ferramentas": "LÂMINA DE 4,3M , ESCARIFICADOR C/ 9 DENTES + 5 DENTES DO RIPPER",
      "Capacidade": "Potência a 2000rpm",
      "Consumo Garantido": "19.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "MG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.06,
      "Preço CPQ 14%": 1459941.02,
      "SPAR": 1401543.3791999999
    }
  },
  {
    "id": 65,
    "codigo": "250-04BLN2.AA",
    "nome": "Minicarregadeira",
    "modelo": "250",
    "familia": "Minicarregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+250",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "ALTO FLUXO E ALTA PRESSÃO (HIGH FLOW XPS), JOYSTICK AVANÇADO, MONITOR AVANÇADO, TECNOLOGIAS DE LEVANTAMENTO, PL, CAMERA DE RÉ, 2 VELOCIDADES, ASSENTO TECIDO, CONTRAPESO ADICIONAL",
      "Contato com o solo": "PNEU 12/16,5",
      "Peso Operacional": "3.551Kg",
      "Motor": "C2.8T - 74hp",
      "Ferramentas": "CACAMBA 1883MM",
      "Capacidade": "Carga max levantamento1.325Kg",
      "Consumo Garantido": "5.0 L/h",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "SSL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 395906.48,
      "SPAR": 380070.22079999995
    }
  },
  {
    "id": 66,
    "codigo": "302.7-01APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "302.7",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+302.7",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE FECHADA,  ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REBATÍVEL",
      "Contato com o solo": "ESTEIRAS DE AÇO",
      "Peso Operacional": "3.050Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,08M³ E 460MM",
      "Capacidade": "Profundidade max escav. 2.710mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.14,
      "Preço CPQ 14%": 299684.41,
      "SPAR": 287697.03359999997
    }
  },
  {
    "id": 67,
    "codigo": "302.7-02APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "302.7",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+302.7",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "CABINE FECHADA,  ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REBATÍVEL",
      "Contato com o solo": "ESTEIRAS DE BORRACHA",
      "Peso Operacional": "3.050Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇMABA DE 0,08M³ E 460MM",
      "Capacidade": "Profundidade max escav. 2.710mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.14,
      "Preço CPQ 14%": 293868.96,
      "SPAR": 282114.20160000003
    }
  },
  {
    "id": 68,
    "codigo": "303.5-01APDC.AA",
    "nome": "Miniescavadeira",
    "modelo": "303.5",
    "familia": "Miniescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+303.5",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": " CABINE  FECHADA, ENGATE RÁPIDO MANUAL, JOYSTICK ELETROHIDRÁULICO, CABINE REBATÍVEL",
      "Contato com o solo": "ESTEIRA DE AÇO",
      "Peso Operacional": "4.190Kg",
      "Motor": "C1.1T - 23,6hp",
      "Ferramentas": "CAÇAMBA DE 0,12M³ E 619MM",
      "Capacidade": "Profundidade max escav. 3.110mm ",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "MHEX",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.095,
      "Preço CPQ 14%": 344361.45,
      "SPAR": 330586.992
    }
  },
  {
    "id": 69,
    "codigo": "316GC-02DLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316%20GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "TERRAPLANAGEM ALCANCE: CABINE ROPS, BRACO 3.0M, LANCA 4,65M",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "14.600Kg",
      "Motor": "C3.6 - 104hp",
      "Ferramentas": "CAÇ GD 0,76M³ (7 DENTES)",
      "Capacidade": "Profundidade max escav. 5.530mm ",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 695674.74,
      "SPAR": 667847.7504
    }
  },
  {
    "id": 70,
    "codigo": "316GC-04DLN3.AA",
    "nome": "Escavadeira",
    "modelo": "316 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+316%20GC",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "TERRAPLANAGEM ALCANCE VALVULA SD: CABINE ROPS, VALVULA AUXILIAR (2 SENTIDOS) E LINHA, BRACO 3.0M, LANCA 4,65M",
      "Contato com o solo": "SAPATA TRIPLA 600MM",
      "Peso Operacional": "14.600Kg",
      "Motor": "C3.6 - 104hp",
      "Ferramentas": "CAÇ 0,65M³ (5 DENTES)",
      "Capacidade": "Profundidade max escav. 5.530mm ",
      "Consumo Garantido": "10.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 692417.95,
      "SPAR": 664721.232
    }
  },
  {
    "id": 71,
    "codigo": "318GC-02BLN3.AA",
    "nome": "Escavadeira",
    "modelo": "318GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+318GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " VALVULA AUXILIAR (2 SENTIDOS) + LINHA, BRACO 2,6M, LANCA 5,1M",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Ferramentas": "CAÇ GD 0,91M",
      "Consumo Garantido": "11.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXSM",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 775889.96,
      "SPAR": 744854.3616
    }
  },
  {
    "id": 72,
    "codigo": "320-02MLN3.AA",
    "nome": "Escavadeira",
    "modelo": "320",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "VALVULA AUXILIAR (2 SENTIDOS) + LINHA, BRACO HD 2,9M, LANCA HD 5,7M",
      "Contato com o solo": "SAPATA GARRA TRIPLA 700MM",
      "Ferramentas": "CAÇ HD 1,4M³",
      "Consumo Garantido": "16.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 919211.12,
      "SPAR": 882442.6751999999
    }
  },
  {
    "id": 73,
    "codigo": "320GC-02OLN3.AA",
    "nome": "Escavadeira",
    "modelo": "320 GC",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+320%20GC",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "VALVULA AUX: VALVULA AUXILIAR E LINHA MARTELO, BRACO 2,9M, LANCA 5,7M",
      "Contato com o solo": "CARRO MÉDIO",
      "Ferramentas": "CAÇ GD 1,16M³",
      "Consumo Garantido": "12.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXMD",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.09,
      "Preço CPQ 14%": 802932.68,
      "SPAR": 770815.3728
    }
  },
  {
    "id": 74,
    "codigo": "336-02BLN2.AA",
    "nome": "Escavadeira",
    "modelo": "336",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+336",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "LINHA MARTELO:  VALVULA E LINHA PARA MARTELO, PROTECAO COMPLETA ROLETES,BRACO 2,55M, LANCA 6,18M",
      "Contato com o solo": "CARRO INFERIOR ESTREITO, SAPATA GARRA DUPLA 600MM",
      "Ferramentas": "CAÇ 2,4M³ COM PROTETOR LATERAL",
      "Consumo Garantido": "26.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 1398135.58,
      "SPAR": 1342210.1568
    }
  },
  {
    "id": 75,
    "codigo": "350-05CLN3.AA",
    "nome": "Escavadeira",
    "modelo": "350",
    "familia": "Escavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+350",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "COM TECNOLOGIA: CABINE DELUXE, MONITOR 10\", LANÇA MASSA 6.55M, BRAÇO DE 2.5M, PROTEÇÃO COMPLETA DOS ROLETES, VENTILADOR REVERSÍVEL, CÂMERA 360, VÁLVULA E LINHA PARA MARTELO, BOMBA DE REABASTECIMENTO, LUZES NO CONTRAPESO, LUZES DE INSPEÇÃO",
      "Contato com o solo": "SAPATA DG DUPLA 600MM",
      "Ferramentas": "CAÇAMBA SD 3.21M3",
      "Consumo Garantido": "34.0 L/h",
      "Fabricação": "Nacional - Piracicaba",
      "Familia": "HEXLG",
      "Industria": "GCI",
      "Desconto Vigente PSC": 0.07,
      "Preço CPQ 14%": 2024912.42,
      "SPAR": 1943915.9231999998
    }
  },
  {
    "id": 76,
    "codigo": "416-01ELN2.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES, DENTES, KEYPAD, PARALAMA,ESTAB. DE BORRACHA,PL",
      "Contato com o solo": "Pneus Goodyear",
      "Consumo Garantido": "-",
      "Fabricação": "Nacional - Campo Largo",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 474143.3,
      "SPAR": 455177.56799999997
    }
  },
  {
    "id": 77,
    "codigo": "416-03CLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES + LINHAS, DENTES, KEYPAD, PARALAMA,ESTAB. DE BORRACHA,PL",
      "Contato com o solo": "Pneus Goodyear",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 489418.72,
      "SPAR": 455159.4096
    }
  },
  {
    "id": 78,
    "codigo": "416-03DLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES + LINHAS, POWERSHIFT, DENTES, KEYPAD, PARALAMA,ESTAB. DE BORRACHA,PL, PROT. DO TANQUE, ENGATE RAPIDO.",
      "Contato com o solo": "Pneus Goodyear",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 510823.76,
      "SPAR": 490390.8096
    }
  },
  {
    "id": 79,
    "codigo": "416-04DLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "MARTELO B8S, CABINE, 4X4, 5 FUNÇÕES + LINHAS, DENTES, KEYPAD, ENGATE RAPIDO MANUAL, PARALAMA,ESTAB. DE BORRACHA,PL",
      "Contato com o solo": "Pneus Goodyear",
      "Ferramentas": "CACAMBA PADRAO INSTALADA",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 535092.1,
      "SPAR": 513688.41599999997
    }
  },
  {
    "id": 80,
    "codigo": "416-06DLN3.AA",
    "nome": "Retroescavadeira",
    "modelo": "416",
    "familia": "Retroescavadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+416",
    "detalhes": {
      "Arranjo": "06",
      "Configuração": "CABINE, 4X4, 5 FUNÇÕES, BORDA, BRAÇO EXTENSÍVEL, PARALAMA, ESTAB. DE BORRACHA, PL",
      "Contato com o solo": "Pneus Goodyear",
      "Familia": "BHL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.063,
      "Preço CPQ 14%": 495901.03,
      "SPAR": 476064.9888
    }
  },
  {
    "id": 81,
    "codigo": "920-02ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "ENGATE Rápido, REC. ELETR, PL, PROT DO A/C, VENTILADOR REVERSIVEL",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Ferramentas": "CAÇ 1,9M³ (IT) BORDA",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 592918.92,
      "SPAR": 569202.1632000001
    }
  },
  {
    "id": 82,
    "codigo": "920-03ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "03",
      "Configuração": "ENGATE Rápido, REC. ELETR, PL, PROT DO A/C, VENTILADOR REVERSIVEL.",
      "Contato com o solo": "PNEU 17.5-25 L2 GD",
      "Ferramentas": "CAÇ 1,9M³ (IT) BORDA+ BIG BAG",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 609089.7,
      "SPAR": 584726.112
    }
  },
  {
    "id": 83,
    "codigo": "920-04ALN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "AGGREGATE:  MI , PROT A/C,  VENTILADOR REVERSIVEL, PL",
      "Contato com o solo": "PNEU 20.5 R25",
      "Ferramentas": "CAÇ 2,0M(PO) BORDA",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 631290.83,
      "SPAR": 606039.1967999999
    }
  },
  {
    "id": 84,
    "codigo": "920-05LN3.AA",
    "nome": "Carregadeira",
    "modelo": "920",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+920",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "MA ,ENGATE RAPIDO IT, PROT A/C, VENTILADOR REVERSIVEL, PL",
      "Contato com o solo": "PNEU 20.5 R25",
      "Ferramentas": "CAÇ 1,9,0M BORDA",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.084,
      "Preço CPQ 14%": 645125.06,
      "SPAR": 619320.0576000001
    }
  },
  {
    "id": 85,
    "codigo": "924-04CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "04",
      "Configuração": "MERCADO DE CONSTRUÇÃO:  PINADO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU RADIAL 20.5R-25 MAXAM",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 763131.2,
      "SPAR": 732605.9519999999
    }
  },
  {
    "id": 86,
    "codigo": "924-05BLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "05",
      "Configuração": "CONSTRUÇÃO RADIAL: PINADO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU RADIAL 20.5R25 MICHELIN",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 804897.48,
      "SPAR": 772701.5808
    }
  },
  {
    "id": 87,
    "codigo": "924-02CLN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": "MERCADO AGRO:  Engate rápido FUSION, CONTRAPESO ADICIONAL, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, CÂMERA DE RÉ, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU DIAGONAL 20.5-25 TITAN",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 792790.97,
      "SPAR": 761079.3311999999
    }
  },
  {
    "id": 88,
    "codigo": "924-01LN3.AA",
    "nome": "Carregadeira",
    "modelo": "924",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+924",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CONTRUÇÃO 17.5 ENGATE: ENGATE RÁPIDO, VENTILADOR REVERSÍVEL, MONITOR 8\", ASSENTO COM SENSOR DE PRESENÇA, PRODUCT LINK DUAL (HÍBRIDO)",
      "Contato com o solo": "PNEU DIAGONAL 17.5-25 GOODYEAR",
      "Ferramentas": "CAÇAMBA 2.1M³, DENTES",
      "Familia": "SWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.092,
      "Preço CPQ 14%": 796290,
      "SPAR": 764438.4
    }
  },
  {
    "id": 89,
    "codigo": "966-02FLN3.AA",
    "nome": "Carregadeira",
    "modelo": "966",
    "familia": "Carregadeira",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+966",
    "detalhes": {
      "Arranjo": "02",
      "Configuração": " MINERIO DE FERRO, 2V COM RIDE CONTROL , EIXO ARREFECIDO, LUZES LED PREMIUM, VENTILADOR PADRÃO,  CONTRAPESO PADRÃO",
      "Contato com o solo": "PNEUS L5",
      "Ferramentas": "CAÇAMBA FERRO 2.80m³",
      "Familia": "MWL",
      "Industria": "BCP",
      "Desconto Vigente PSC": 0.075,
      "Preço CPQ 14%": 1816161.76,
      "SPAR": 1743515.2896
    }
  },
  {
    "id": 90,
    "codigo": "707-01LN3.AA",
    "nome": "Fora de estrada",
    "modelo": "707",
    "familia": "Fora de estrada",
    "imagem": "https://placehold.co/600x400/FFCC09/000000?text=CAT+707",
    "detalhes": {
      "Arranjo": "01",
      "Configuração": "CAMINHÃO \"DUMPER\" CONCEBIDO PARA SER UTILIZADO FORA-DE-ESTRADA",
      "Motor": "C13",
      "Capacidade": "66T",
      "Consumo Garantido": "-",
      "Fabricação": "Importado - India",
      "Familia": "AT",
      "Industria": "GCI",
      "SPAR": 0
    }
  }
];